<?php
	require_once(dirname($_SERVER['DOCUMENT_ROOT']) . "/cgi-bin/functions.php");
	require_once(dirname($_SERVER['DOCUMENT_ROOT']) . "/root/yeni_ekran/dashboard_repostory/kullaniciKontrolClass.php");
	
	class dashboardClass extends kullaniciKontrolClass{

		protected $cdb;
		protected $hasarTable;					
		protected $companyId;			
		protected $kullaniciKriter;	
		protected $otodisiKullaniciKriter;
		protected $OTODISI_DOSYA_SORUMLUSU;
		protected $DEF_DOSYA_SORUMLUSU;
		function __construct()
		{
			global $SESSION;
			require_valid_login();
			$this->cdb 				= new db_layer;			
			$this->hasarTable   	= get_hasar_table();									
			$this->companyId 		= OAConf::COMPANY_ID;						
			$this->USER_NAME		= $SESSION['username'];  			
			$this->USER_ID			= $SESSION['user_id'];  						
			$this->kullaniciKontrol();				
						
		}		

		function eksperBlok($ay_basi,$ay_sonu,$sorumlu,$brans,$servis_turu){			
			
			if( ($this->kullaniciKontrol() == '2' || $this->hdsKullaniciKriter) ) { return false;}
			
			if(($sorumlu!=NULL && $sorumlu!=-1)){ 
				$kriter .=  " AND DS.ID='$sorumlu'";
			}		
			
			if($brans!=NULL && $brans!=-1){ 
				$kriter .=  " AND H.SIGORTA_SEKLI='$brans'";
			}			
			
			
			if($servis_turu==1){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1'";}
			if($servis_turu==2){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0'";}
			if($servis_turu==3){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==4){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==5){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==6){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==7){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==8){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='0'";}
			
			
			$sql = " 
					SELECT * FROM 
					(
						SELECT
							/*eksper blok*/
							COUNT(DISTINCT H.ID) AS TOPLAM_DOSYA_SAYISI,
							FORMAT(AVG( DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)),0) AS DOSYA_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS DOSYA_30_GECEN_SURE,
							
							COUNT(DISTINCT H.ID) AS TOPLAM_ADET,							
							
							COUNT(DISTINCT IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30,H.ID,NULL )) AS POLICE_FARK_DOSYA_SAY,
							FORMAT(AVG( IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30, DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT),NULL)),0) AS POLICE_FARK_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30, H.ID,NULL)) AS POLICE_FARK_30_GECEN_SURE,													
							
							COUNT(DISTINCT IF(H.SERVIS_ID IS NULL, H.ID, NULL)) AS SERVIS_GIRILMEMIS_DOSYA_ADET,
							FORMAT( AVG(  IF ( H.SERVIS_ID IS NULL , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS SERVIS_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SERVIS_ID IS NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS SERVIS_GIRILMEMIS_30_ADET,
							
							COUNT(DISTINCT IF(H.ON_RAPOR=1,H.ID,NULL)) AS ON_RAPO_ADET,
							FORMAT( AVG(  IF ( H.ON_RAPOR=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ON_RAPOR_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.ON_RAPOR=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ON_RAPOR_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.ON_RAPOR,0)=0,H.ID,NULL)) AS ON_RAPO_GONDERILMEYEN_ADET,
							FORMAT( AVG(  IF ( IFNULL(H.ON_RAPOR,0)=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ON_RAPO_GONDERILMEYEN_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.ON_RAPOR,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ON_RAPO_GONDERILMEYEN_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.PERT,0)=1,H.ID,NULL)) AS PERT_ADET,
							FORMAT( AVG( IF ( IFNULL(H.PERT,0)=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS PERT_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.PERT,0)=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS PERT_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0, H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA,
							FORMAT( AVG(  IF ( IFNULL(H.TAHMINI_HASAR,0)=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_30_ADET,

							COUNT(DISTINCT IF(H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1, H.ID, NULL)) AS SIPARIS_UYGUN_DOSYALAR,
							FORMAT( AVG(  IF (H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS SIPARIS_UYGUN_DOSYALAR_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS SIPARIS_UYGUN_DOSYALAR_30_ADET,

							FORMAT(SUM(H.SS_TAHMINI_HASAR),2) AS IHBAR_MUALLAK_TUTAR,
							FORMAT(SUM(H.TAHMINI_HASAR),2) AS EKSPER_MUALLAK_TUTAR,						

							COUNT(DISTINCT IF(H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0), H.ID, NULL)) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS,
							FORMAT( AVG(  IF (H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0), DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0) AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS_30_ADET,						

							COUNT(DISTINCT IF(H.RUCU =1, H.ID, NULL)) AS RUCU_ISARETLI,
							FORMAT( AVG(  IF ( H.RUCU =1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS RUCU_ISARETLI_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.RUCU =1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS RUCU_ISARETLI_30_ADET,
						
							COUNT(DISTINCT IF(H.FOTOVAR=0 , H.ID, NULL)) AS FOTO_EVRAK_YUKLENMEMIS_ADET,
							FORMAT( AVG(   IF( H.FOTOVAR=0 , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS FOTO_EVRAK_YUKLENMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.FOTOVAR=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS FOTO_EVRAK_YUKLENMEMIS_30_ADET
						FROM
							$this->hasarTable H							
							LEFT JOIN HASAR_MAGDUR_ARACLAR HMA ON H.ONAY_NO = HMA.ONAY_NO										
							LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME							
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						WHERE 
							H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
							AND IFNULL(H.DOSYA_STATU,0) = 0
							AND IFNULL(U.HKM_EKSPER,0) = 0
							AND IFNULL(FATURALI_KULLANICI,0)= 0
							AND IFNULL(U.OTOMOTIV,0) = 0
							AND H.DOSYA_NO NOT LIKE '%TEST%'
							$kriter
							$this->kullaniciKriter
					)
						AS T1 CROSS JOIN
					(
						SELECT 
							COUNT( DISTINCT 
									CASE 
									WHEN IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=1 THEN  H.ID
									WHEN IFNULL(HD.VERITABANINDA,0) <> 1 AND HD.ISLEM=1 THEN  H.ID
									END 
							) AS DEGISIM_ADET,						
							COUNT( DISTINCT
								CASE 
								WHEN HD.ISLEM=1 AND HD.MINI_ID=0 AND ((IFNULL(HD.SOKTAK,0) + IFNULL(HD.BOYA_TUTAR,0) + IFNULL(HD.TAMIR,0))>0) THEN H.ID
								WHEN IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=2 THEN  H.ID
								WHEN IFNULL(HD.VERITABANINDA,0) <> 1 AND HD.ISLEM=2 THEN  H.ID
								WHEN HD.ISLEM=3 THEN H.ID
								END 
							) AS ONARIM_ADET,
							FORMAT( AVG( IF ( HD.ISLEM = 1 , DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT )  ,NULL)),0) AS DEGISIM_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(HD.ISLEM =1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS DEGISIM_30_ADET,
							
							FORMAT( AVG( IF ( HD.ISLEM NOT IN (1) ,  DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ONARIM_ORT_GECEN_SURE,		
							COUNT(DISTINCT IF(HD.ISLEM NOT IN (1) AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ONARIM_30_ADET,
							
							COUNT(DISTINCT IF(HD.ID IS NULL, H.ID,NULL)) AS PARCA_GIRILMEMIS_DOSYA_ADET,
							FORMAT( AVG( IF ( HD.ID IS NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS PARCA_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(HD.ID IS NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS PARCA_GIRILMEMIS_30_ADET
						FROM 
							$this->hasarTable H
							LEFT JOIN HASAR_DETAIL HD ON H.ONAY_NO = HD.ONAY_NO		
							LEFT JOIN SIPARIS_DETAIL SD ON HD.ID = SD.YEDPAR_ID									
							INNER JOIN USERS U ON U.U_NAME  = H.USER_EKSPER	
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						WHERE 
							H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
							AND IFNULL(H.DOSYA_STATU,0) = 0
							AND IFNULL(U.HKM_EKSPER,0) = 0
							AND IFNULL(FATURALI_KULLANICI,0)= 0
							AND IFNULL(U.OTOMOTIV,0) = 0
							AND H.DOSYA_NO NOT LIKE '%TEST%'
							$kriter 
							$this->kullaniciKriter
					) AS T2		
					CROSS JOIN
					(
						SELECT 
							SUM(TN.NEDEN_ACIK_DOSYALAR) AS NEDEN_ACIK_DOSYALAR,
							FORMAT(SUM(TN.NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE) / SUM(TN.NEDEN_ACIK_DOSYALAR),0)AS NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE,
							SUM(TN.NEDEN_ACIK_DOSYALAR_30_ADET) AS NEDEN_ACIK_DOSYALAR_30_ADET
						FROM 
						(	SELECT
								COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL, H.ID, NULL)) AS NEDEN_ACIK_DOSYALAR, 
								FORMAT( AVG(  IF ( NA.ACIK_NOTU IS NOT NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS NEDEN_ACIK_DOSYALAR_30_ADET
							FROM
								$this->hasarTable H
							INNER JOIN USERS U ON U.U_NAME = H.USER_EKSPER
							INNER JOIN NEDEN_ACIK NA ON H.ID = NA.DOSYA_ID
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
							WHERE
								H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
								AND IFNULL(H.DOSYA_STATU,0) = 0
								AND IFNULL(U.HKM_EKSPER,0) = 0
								AND IFNULL(FATURALI_KULLANICI,0)= 0
								AND IFNULL(U.OTOMOTIV,0) = 0
								AND H.DOSYA_NO NOT LIKE '%TEST%'
								$kriter 
								$this->kullaniciKriter
						GROUP BY H.ID) AS TN 
					) AS T3		
				";
				//if(dbg()) { echo($sql); die; }
			if (!($this->cdb->execute_sql($sql,$result,$error_msg))){return false;}
			$row = mysql_fetch_object($result);
			return $row;	
		}
		
		function eksperBlokOtodisi($ay_basi,$ay_sonu,$sorumlu,$brans){
		
		
			if($this->kullaniciKontrol() == '1' || $this->hdsKullaniciKriter) { return false;}
			
			
					
			if(($sorumlu!=NULL && $sorumlu!=-1)){ 
				$kriter .=  " AND DS.ID='$sorumlu'";
				
			}
			
			if($brans!=NULL && $brans!=-1){ 
				$kriter .=  " AND H.POLICE_TURU_ID='$brans'";
			}			
			
			
			$sql = " 
					SELECT * FROM 
					(
					SELECT
						/*eksper blok otodisi*/
						H.ID AS H_ID,
						S.AD AS BRANS,
						H.DOSYA_NO,
						LEFT(U.NAME,30) AS EKSPER,		
						H.HASAR_TARIHI,
						H.KAYIT_TARIH_SAAT,						
						
						COUNT(DISTINCT H.ID) AS TOPLAM_DOSYA_SAYISI,
						FORMAT(AVG( DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)),0) AS DOSYA_ORT_GECEN_SURE,
						COUNT(DISTINCT IF(DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS DOSYA_30_GECEN_SURE,
						
						COUNT(DISTINCT H.ID) AS TOPLAM_ADET,
						
						COUNT(DISTINCT IF(H.ON_RAPOR=1,H.ID,NULL)) AS ON_RAPOR_ADET,
						FORMAT( AVG(  IF ( H.ON_RAPOR=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ON_RAPOR_ORT_GECEN_SURE,
						COUNT(DISTINCT IF(H.ON_RAPOR=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ON_RAPOR_30_ADET,
						
						COUNT(DISTINCT IF(IFNULL(H.ON_RAPOR,0)=0,H.ID,NULL)) AS ON_RAPOR_GONDERILMEYEN_ADET,
						FORMAT( AVG(  IF ( IFNULL(H.ON_RAPOR,0)=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ON_RAPOR_GONDERILMEYEN_ORT_GECEN_SURE,
						COUNT(DISTINCT IF(IFNULL(H.ON_RAPOR,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ON_RAPOR_GONDERILMEYEN_30_ADET,
						
						COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0, H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA,
						FORMAT( AVG(  IF ( IFNULL(H.TAHMINI_HASAR,0)=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA_ORT_GECEN_SURE,
						COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_30_ADET,

						".( ($this->companyId != 20 || $this->companyId != 70) ? "
						FORMAT(SUM(H.IHBAR_TAHMINI_HASAR),2) AS IHBAR_MUALLAK_TUTAR, 
						" : "" )."	
						FORMAT(SUM(H.TAHMINI_HASAR),2) AS EKSPER_MUALLAK_TUTAR,						
						
						COUNT(DISTINCT IF(F.FOTO_ADET=0 OR F.EVRAK_ADET=0, H.ID, NULL)) AS FOTO_EVRAK_YUKLENMEMIS_ADET,
						FORMAT( AVG( IF ( F.FOTO_ADET=0 OR F.EVRAK_ADET=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS FOTO_EVRAK_YUKLENMEMIS_ORT_GECEN_SURE,
						COUNT(DISTINCT IF(F.FOTO_ADET=0 OR F.EVRAK_ADET=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS FOTO_EVRAK_YUKLENMEMIS_30_ADET,					

						COUNT(DISTINCT IF(H.RUCU =1, H.ID, NULL)) AS RUCU_ISARETLI,
						FORMAT( AVG(  IF ( H.RUCU =1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS RUCU_ISARETLI_ORT_GECEN_SURE,
						COUNT(DISTINCT IF(H.RUCU =1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS RUCU_ISARETLI_30_ADET
					FROM
						YANGIN_HASAR H									
					LEFT JOIN USERS U ON H.USER_ID = U.ID					
					LEFT JOIN YANGIN_HASAR_FE_ADET F ON F.HASAR_ID = H.ID 
					INNER JOIN YANGIN_HASAR_SEKLI S ON S.ID = H.POLICE_TURU_ID	
					LEFT JOIN YANGIN_DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
					WHERE
					H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
					AND IFNULL(H.DOSYA_STATU,0) = 0
					AND H.DOSYA_NO NOT LIKE '%TEST%'					
					".$this->otodisiKullaniciKriter."
					) AS T1
					CROSS JOIN
					(
						SELECT 
							COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL, H.ID, NULL)) AS NEDEN_ACIK_DOSYALAR, 
							FORMAT( AVG(  IF ( NA.ACIK_NOTU IS NOT NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS NEDEN_ACIK_DOSYALAR_30_ADET
						FROM 
							YANGIN_HASAR H
							LEFT JOIN USERS U ON H.USER_ID = U.ID
							INNER JOIN ( SELECT DOSYA_ID,ACIK_NOTU FROM YANGIN_NEDEN_ACIK GROUP BY DOSYA_ID) NA ON  H.ID = NA.DOSYA_ID
							LEFT JOIN YANGIN_DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						WHERE
							H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
							AND IFNULL(H.DOSYA_STATU,0) = 0
							AND H.DOSYA_NO NOT LIKE '%TEST%'							
							".$this->otodisiKullaniciKriter."
					) AS T2						
				";	
			//if(dbg()){ECHO  $sql;}		
			if (!($this->cdb->execute_sql($sql,$result,$error_msg))){return false;}
			$row = mysql_fetch_object($result);
			return $row;	
		}
		
		function servisBlok($ay_basi,$ay_sonu,$sorumlu,$brans,$servis_turu){

			if( ($this->kullaniciKontrol() == '2') ) { return false;}		
			
			if(($sorumlu!=NULL && $sorumlu!=-1)){ 
				$kriter .=  " AND DS.ID='$sorumlu'";
				
			}
			
			if($brans!=NULL && $brans!=-1){ 
				$kriter .=  " AND H.SIGORTA_SEKLI='$brans'";
			}

			if($servis_turu==1){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1'";}
			if($servis_turu==2){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0'";}
			if($servis_turu==3){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==4){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==5){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==6){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==7){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==8){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='0'";}
			
			$sql = " 
					SELECT * FROM 
						(
							SELECT		
								COUNT( DISTINCT H.ID) AS TOPLAM_DOSYA_SAYISI,
								COUNT(DISTINCT IF( H.DOSYA_STATU = 0 AND IFNULL(HDO.DOSYA_ID,0)=0,H.ID,NULL)) SERVISTE_ACIK,
								FORMAT( AVG( IF ( H.DOSYA_STATU = 0 AND IFNULL(HDO.DOSYA_ID,0)=0, DATEDIFF(NOW(), H.KAYIT_TARIH_SAAT), NULL ) ),0 ) AS SERVISTE_ACIK_ORT_SURE,
								COUNT(DISTINCT IF(H.DOSYA_STATU = 0 AND IFNULL(HDO.DOSYA_ID,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS SERVISTE_ACIK_ORT_SURE_30_ADET,
								
								COUNT(DISTINCT IF(H.DOSYA_STATU = 1 AND HDO.DOSYA_ID IS NULL=1,H.ID,NULL)) SERVISTE_KAPALI_SIGORTA_ONAY_BEKLIYOR,
								FORMAT( AVG( IF ( H.SERVIS_DOSYA =1 AND H.DOSYA_STATU = 1 AND HDO.DOSYA_ID IS NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS SERVISTE_KAPALI_SIGORTA_ONAY_BEKLIYOR_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(H.SERVIS_DOSYA =1 AND H.DOSYA_STATU = 1 AND HDO.DOSYA_ID IS NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS SERVISTE_KAPALI_SIGORTA_ONAY_BEKLIYOR_30_ADET,
								
								COUNT(DISTINCT IF(H.SERVIS_DOSYA =1 AND H.DOSYA_STATU = 1 AND HDO.DURUM_ID =2,H.ID,NULL)) AS EKSPER_GOREVLENDIRILEN,
								FORMAT( AVG( IF ( H.SERVIS_DOSYA =1 AND H.DOSYA_STATU = 1 AND HDO.DURUM_ID =2, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )  ,NULL)),0) AS EKSPER_GOREVLENDIRILEN_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(H.SERVIS_DOSYA =1 AND H.DOSYA_STATU = 1 AND HDO.DOSYA_ID IS NULL AND HDO.DURUM_ID =2 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS EKSPER_GOREVLENDIRILEN_30_ADET,
								
								COUNT(DISTINCT IF( IFNULL(HDO.DOSYA_ID,0) = 0 AND IFNULL(HDD.ID,0)=0 AND H.CLOSER_DATE IS NULL,H.ID,NULL)) ILK_ONAYA_GITMEYENLER,
								FORMAT( AVG( IF( IFNULL(HDO.DOSYA_ID,0) = 0 AND IFNULL(HDD.ID,0)=0 AND H.CLOSER_DATE IS NULL, DATEDIFF(NOW(), H.KAYIT_TARIH_SAAT), NULL ) ),0 ) AS ILK_ONAYA_GITMEYENLER_ORT_SURE,
								COUNT(DISTINCT IF(IFNULL(HDO.DOSYA_ID,0) = 0 AND IFNULL(HDD.ID,0)=0 AND H.CLOSER_DATE IS NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ILK_ONAYA_GITMEYENLER_30_ADET,
								
								COUNT(DISTINCT IF(H.FOTOVAR=0 , H.ID, NULL)) AS FOTO_EVRAK_YUKLENMEMIS_ADET,
								FORMAT( AVG(  IF( H.FOTOVAR=0 , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS FOTO_EVRAK_YUKLENMEMIS_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(H.FOTOVAR=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS FOTO_EVRAK_YUKLENMEMIS_30_ADET,								
								
								SUM(IF(H.DOSYA_STATU = 1 AND HDO.DOSYA_ID IS NOT NULL=1,1,0)) SERVISTE_KAPALI_SIGORTA_DA_KAPALI				 						
							FROM
								$this->hasarTable H
								INNER JOIN HKMEKS_DOSYA_SORUMLULARI HDS ON HDS.DOSYA_ID = H.ID
								INNER JOIN USERS U ON U.U_NAME  = H.USER_EKSPER						
								LEFT JOIN HKMEKS_DOSYA_ONAY HDO ON HDO.DOSYA_ID = H.ID
								LEFT JOIN HKMEKS_DOSYA_DETAY HDD ON HDD.DOSYA_ID = H.ID	
								LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU								
							WHERE  
									H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
									AND IFNULL(H.SERVIS_DOSYA,0) =1 
									AND IFNULL(U.OTOMOTIV,0) !=1 							
									AND IFNULL(U.HKM_EKSPER,0)=1 							
									AND IFNULL(U.FATURALI_KULLANICI,0)=1
									AND H.DOSYA_NO NOT LIKE '%TEST%'
									AND IFNULL(HDO.DURUM_ID,0)=0 									
									$kriter					
									$this->hdsKullaniciKriter
							)
							AS T1 CROSS JOIN
							(
						SELECT 		  
							COUNT(DISTINCT IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30,H.ID,NULL )) AS POLICE_FARK_DOSYA_SAY,
							FORMAT(AVG( IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30, DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT),NULL)),0) AS POLICE_FARK_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30, H.ID,NULL)) AS POLICE_FARK_30_GECEN_SURE,
							
							COUNT( DISTINCT IF(AD.SERVIS_ONAYSIZ =2,AD.ID,NULL)) AS TOTAL_MBL_BEKLEYEN,						
							FORMAT( AVG( IF ( AD.SERVIS_ONAYSIZ =2 , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )  ,NULL)),0) AS TOTAL_MBL_BEKLEYEN_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(AD.SERVIS_ONAYSIZ =2 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS TOTAL_MBL_BEKLEYEN_30_ADET,
							
							COUNT(DISTINCT IF(H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1, H.ID, NULL)) AS SIPARIS_UYGUN_DOSYALAR,
							FORMAT( AVG(  IF ( H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS SIPARIS_UYGUN_DOSYALAR_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS SIPARIS_UYGUN_DOSYALAR_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0, H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA,
							FORMAT( AVG(  IF ( IFNULL(H.TAHMINI_HASAR,0)=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_30_ADET,							
							
							FORMAT(AVG(DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)),0) AS DOSYA_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS DOSYA_30_GECEN_SURE,
							
							COUNT(DISTINCT IF(H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0), H.ID, NULL)) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS,
							FORMAT( AVG(  IF (H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0), DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0) AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS_30_ADET
						FROM $this->hasarTable H 
							INNER JOIN HKMEKS_DOSYA_SORUMLULARI HDS ON HDS.DOSYA_ID = H.ID										
							LEFT JOIN USERS U ON U.U_NAME  = H.USER_EKSPER	
							LEFT JOIN HASAR_MAGDUR_ARACLAR HMA ON H.ONAY_NO = HMA.ONAY_NO																									
							LEFT JOIN HKMEKS_DOSYA_ONAY HDO ON HDO.DOSYA_ID = H.ID						
							LEFT JOIN ( SELECT H.KAYIT_TARIH_SAAT,AD.ID, AD.SERVIS_ONAYSIZ, A.DOSYA_ID FROM AUTOKING_DETAIL AD INNER JOIN AUTOKING A ON A.ID = AD.AUTOKING_ID LEFT JOIN $this->hasarTable H ON A.DOSYA_ID = H.ID WHERE AD.SERVIS_ONAYSIZ = 2 AND H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59' AND IFNULL(H.SERVIS_DOSYA,0) =1 GROUP BY H.ID) AD ON AD.DOSYA_ID = H.ID
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						WHERE 
								H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
								AND IFNULL(H.SERVIS_DOSYA,0) =1 
								AND IFNULL(U.OTOMOTIV,0) !=1 							
								AND IFNULL(U.HKM_EKSPER,0)=1 							
								AND IFNULL(U.FATURALI_KULLANICI,0)=1
								AND H.DOSYA_NO NOT LIKE '%TEST%'
								AND IFNULL(HDO.DURUM_ID,0)=0 
								$kriter	
								$this->hdsKullaniciKriter								
				) AS T2	CROSS JOIN				
				(
					SELECT 
						COUNT( DISTINCT
							CASE 
							WHEN H.SERVIS_DOSYA =1 AND IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=1 THEN  H.ID
							WHEN H.SERVIS_DOSYA =1 AND IFNULL(HD.VERITABANINDA,0) != 1 AND HD.ISLEM=1 THEN  H.ID
							END 
						) AS DEGISIM_ADET,
						COUNT( DISTINCT 
							CASE 
							WHEN H.SERVIS_DOSYA =1 AND HD.ISLEM=1 AND HD.MINI_ID=0 AND ((IFNULL(HD.SOKTAK,0) + IFNULL(HD.BOYA_TUTAR,0) + IFNULL(HD.TAMIR,0))>0) THEN H.ID
							WHEN H.SERVIS_DOSYA =1 AND IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=2 THEN  H.ID
							WHEN H.SERVIS_DOSYA =1 AND IFNULL(HD.VERITABANINDA,0) <> 1 AND HD.ISLEM=2 THEN  H.ID
							WHEN H.SERVIS_DOSYA =1 AND HD.ISLEM=3 THEN H.ID
							END 
						) AS ONARIM_ADET,
						
						FORMAT( AVG( IF ( HD.ISLEM = 1 , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )  ,NULL)),0) AS DEGISIM_ORT_GECEN_SURE,
						COUNT(DISTINCT IF(HD.ISLEM =1 AND DATEDIFF(NOW(), H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS DEGISIM_30_ADET,
						
						FORMAT( AVG( CASE 
								WHEN HD.ISLEM=1 AND HD.MINI_ID=0 AND ((IFNULL(HD.SOKTAK,0) + IFNULL(HD.BOYA_TUTAR,0) + IFNULL(HD.TAMIR,0))>0) THEN DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )
								WHEN IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=2 THEN  DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )
								WHEN IFNULL(HD.VERITABANINDA,0) <> 1 AND HD.ISLEM=2 THEN  DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )
								WHEN HD.ISLEM=3 THEN DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )
							  END),0) AS ONARIM_ORT_GECEN_SURE,
						COUNT( DISTINCT CASE 
								WHEN HD.ISLEM=1 AND HD.MINI_ID=0 AND ((IFNULL(HD.SOKTAK,0) + IFNULL(HD.BOYA_TUTAR,0) + IFNULL(HD.TAMIR,0))>0) AND DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT )>30 THEN H.ID
								WHEN IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=2 AND DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT )>30 THEN H.ID
								WHEN IFNULL(HD.VERITABANINDA,0) <> 1 AND HD.ISLEM=2 AND DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT )>30 THEN H.ID
								WHEN HD.ISLEM=3 AND DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT )>30 THEN H.ID
							  END) AS ONARIM_30_ADET,
						
						COUNT(DISTINCT IF(H.SERVIS_DOSYA =1 AND H.DOSYA_STATU = 0 AND IFNULL(HDS.DOSYA_ID,0)>0,H.ID,NULL)) ACIK_DOSYA_SIGORTA_KUL_MESAJ,
						FORMAT( AVG( IF ( H.SERVIS_DOSYA =1 AND H.DOSYA_STATU = 0 AND IFNULL(HDS.DOSYA_ID,0)>0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ACIK_DOSYA_SIGORTA_KUL_MESAJ_ORT_GECEN_SURE,
						COUNT(DISTINCT IF(H.SERVIS_DOSYA =1 AND H.DOSYA_STATU = 0 AND IFNULL(HDS.DOSYA_ID,0)>0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ACIK_DOSYA_SIGORTA_KUL_MESAJ_30_ADET,
						
						COUNT(DISTINCT IF(HD.ID IS NULL, H.ID,NULL)) AS PARCA_GIRILMEMIS_DOSYA_ADET,
						FORMAT( AVG( IF ( HD.ID IS NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS PARCA_GIRILMEMIS_ORT_GECEN_SURE,
						COUNT(DISTINCT IF(HD.ID IS NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS PARCA_GIRILMEMIS_30_ADET  
					FROM 	
						$this->hasarTable H							
						LEFT JOIN USERS U ON U.U_NAME  = H.USER_EKSPER						
						LEFT JOIN HASAR_DETAIL HD ON H.ONAY_NO = HD.ONAY_NO																	
						LEFT JOIN HKMEKS_DOSYA_ONAY HDO ON HDO.DOSYA_ID = H.ID
						LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						LEFT JOIN HKMEKS_DOSYA_SORUMLULARI HDS ON HDS.DOSYA_ID= H.ID AND HDS.MESAJ=1 AND HDS.ONAY=0
					WHERE 
							H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
							AND IFNULL(H.SERVIS_DOSYA,0) =1 
							AND IFNULL(U.OTOMOTIV,0) !=1 							
							AND IFNULL(U.HKM_EKSPER,0)=1 							
							AND IFNULL(U.FATURALI_KULLANICI,0)=1
							AND H.DOSYA_NO NOT LIKE '%TEST%'
							AND IFNULL(HDO.DURUM_ID,0)=0 							
							$kriter
							$this->hdsKullaniciKriter
				) AS T3
				CROSS JOIN
				(
					SELECT 
							SUM(TN.NEDEN_ACIK_DOSYALAR) AS NEDEN_ACIK_DOSYALAR,
							FORMAT(SUM(TN.NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE) / SUM(TN.NEDEN_ACIK_DOSYALAR),0)AS NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE,
							SUM(TN.NEDEN_ACIK_DOSYALAR_30_ADET) AS NEDEN_ACIK_DOSYALAR_30_ADET
						FROM 
						(	SELECT
								COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL, H.ID, NULL)) AS NEDEN_ACIK_DOSYALAR, 
								FORMAT( AVG(  IF ( NA.ACIK_NOTU IS NOT NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS NEDEN_ACIK_DOSYALAR_30_ADET
							FROM
								$this->hasarTable H
								INNER JOIN USERS U ON U.U_NAME = H.USER_EKSPER
								INNER JOIN NEDEN_ACIK NA ON H.ID = NA.DOSYA_ID
								INNER JOIN HKMEKS_DOSYA_SORUMLULARI HDS ON HDS.DOSYA_ID = H.ID
								LEFT JOIN HKMEKS_DOSYA_ONAY HDO ON HDO.DOSYA_ID = H.ID								
								LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
							WHERE
								H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
								AND IFNULL(H.SERVIS_DOSYA,0) =1 
								AND IFNULL(U.OTOMOTIV,0) !=1 							
								AND IFNULL(U.HKM_EKSPER,0)=1 							
								AND IFNULL(U.FATURALI_KULLANICI,0)=1
								AND H.DOSYA_NO NOT LIKE '%TEST%'
								AND IFNULL(HDO.DURUM_ID,0)=0 								
								$kriter 
								$this->hdsKullaniciKriter
							GROUP BY H.ID
						) AS TN 
				) AS T4
				";
			// if(dbg()){ echo $sql; die;}
			if (!($this->cdb->execute_sql($sql,$result,$error_msg))){return false;}
			$row = mysql_fetch_object($result);
			return $row;	
		}
		
		
		function faturaliBlok($ay_basi,$ay_sonu,$sorumlu,$brans,$servis_turu){
		
			if( ($this->kullaniciKontrol() == '2' || $this->hdsKullaniciKriter) ) { return false;}		
		
			if(($sorumlu!=NULL && $sorumlu!=-1)){ 
				$kriter .=  " AND DS.ID='$sorumlu'";
				
			} 
			
			if($brans!=NULL && $brans!=-1){ 
				$kriter .=  " AND H.SIGORTA_SEKLI='$brans'";
			}
			
			if($servis_turu==1){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1'";}
			if($servis_turu==2){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0'";}
			if($servis_turu==3){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==4){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==5){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==6){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==7){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==8){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='0'";}
		
			$sql = " 
					SELECT * FROM 
					(
						SELECT
							/*faturali blok*/
							COUNT(DISTINCT H.ID) AS TOPLAM_DOSYA_SAYISI,
							FORMAT(AVG( DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)),0) AS DOSYA_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS DOSYA_30_GECEN_SURE,
							
							COUNT(DISTINCT H.ID) AS TOPLAM_ADET,							
							
							COUNT(DISTINCT IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30,H.ID,NULL )) AS POLICE_FARK_DOSYA_SAY,
							FORMAT(AVG( IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30, DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT),NULL)),0) AS POLICE_FARK_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30, H.ID,NULL)) AS POLICE_FARK_30_GECEN_SURE,													
							
							COUNT(DISTINCT IF(H.SERVIS_ID IS NULL, H.ID, NULL)) AS SERVIS_GIRILMEMIS_DOSYA_ADET,
							FORMAT( AVG(  IF ( H.SERVIS_ID IS NULL , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS SERVIS_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SERVIS_ID IS NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS SERVIS_GIRILMEMIS_30_ADET,
							
							COUNT(DISTINCT IF(H.ON_RAPOR=1,H.ID,NULL)) AS ON_RAPO_ADET,
							FORMAT( AVG(  IF ( H.ON_RAPOR=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ON_RAPOR_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.ON_RAPOR=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ON_RAPOR_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.ON_RAPOR,0)=0,H.ID,NULL)) AS ON_RAPO_GONDERILMEYEN_ADET,
							FORMAT( AVG(  IF ( IFNULL(H.ON_RAPOR,0)=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ON_RAPO_GONDERILMEYEN_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.ON_RAPOR,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ON_RAPO_GONDERILMEYEN_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.PERT,0)=1,H.ID,NULL)) AS PERT_ADET,
							FORMAT( AVG( IF ( IFNULL(H.PERT,0)=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS PERT_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.PERT,0)=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS PERT_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0, H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA,
							FORMAT( AVG(  IF ( IFNULL(H.TAHMINI_HASAR,0)=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_30_ADET,

							COUNT(DISTINCT IF(H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1, H.ID, NULL)) AS SIPARIS_UYGUN_DOSYALAR,
							FORMAT( AVG(  IF (H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS SIPARIS_UYGUN_DOSYALAR_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS SIPARIS_UYGUN_DOSYALAR_30_ADET,

							FORMAT(SUM(H.SS_TAHMINI_HASAR),2) AS IHBAR_MUALLAK_TUTAR,
							FORMAT(SUM(H.TAHMINI_HASAR),2) AS EKSPER_MUALLAK_TUTAR,						

							COUNT(DISTINCT IF(H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0), H.ID, NULL)) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS,
							FORMAT( AVG(  IF (H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0), DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0) AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS_30_ADET,						

							COUNT(DISTINCT IF(H.RUCU =1, H.ID, NULL)) AS RUCU_ISARETLI,
							FORMAT( AVG(  IF ( H.RUCU =1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS RUCU_ISARETLI_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.RUCU =1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS RUCU_ISARETLI_30_ADET,
							
							COUNT(DISTINCT IF(H.FOTOVAR=0 , H.ID, NULL)) AS FOTO_EVRAK_YUKLENMEMIS_ADET,
							FORMAT( AVG( IF ( H.FOTOVAR=0 , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS FOTO_EVRAK_YUKLENMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.FOTOVAR=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS FOTO_EVRAK_YUKLENMEMIS_30_ADET
						FROM
							$this->hasarTable H							
							LEFT JOIN HASAR_MAGDUR_ARACLAR HMA ON H.ONAY_NO = HMA.ONAY_NO										
							LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME							
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						WHERE 
							H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
							AND (IFNULL(U.FATURALI_KULLANICI, 0) = '1'  AND IFNULL(U.HKM_EKSPER, 0) = 0 AND IFNULL(U.OTOMOTIV,0)!=1) 
							AND IFNULL(H.DOSYA_STATU,0)=0	
							AND H.DOSYA_NO NOT LIKE '%TEST%'							
							$kriter
							$this->kullaniciKriter
					)
						AS T1 CROSS JOIN
					(
						SELECT 
							COUNT( DISTINCT 
									CASE 
									WHEN IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=1 THEN  H.ID
									WHEN IFNULL(HD.VERITABANINDA,0) <> 1 AND HD.ISLEM=1 THEN  H.ID
									END 
							) AS DEGISIM_ADET,						
							COUNT( DISTINCT
								CASE 
								WHEN HD.ISLEM=1 AND HD.MINI_ID=0 AND ((IFNULL(HD.SOKTAK,0) + IFNULL(HD.BOYA_TUTAR,0) + IFNULL(HD.TAMIR,0))>0) THEN H.ID
								WHEN IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=2 THEN  H.ID
								WHEN IFNULL(HD.VERITABANINDA,0) <> 1 AND HD.ISLEM=2 THEN  H.ID
								WHEN HD.ISLEM=3 THEN H.ID
								END 
							) AS ONARIM_ADET,
							FORMAT( AVG( IF ( HD.ISLEM = 1 , DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT )  ,NULL)),0) AS DEGISIM_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(HD.ISLEM =1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS DEGISIM_30_ADET,
							
							FORMAT( AVG( IF ( HD.ISLEM NOT IN (1) ,  DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ONARIM_ORT_GECEN_SURE,		
							COUNT(DISTINCT IF(HD.ISLEM NOT IN (1) AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ONARIM_30_ADET,
							
							COUNT(DISTINCT IF(HD.ID IS NULL, H.ID,NULL)) AS PARCA_GIRILMEMIS_DOSYA_ADET,
							FORMAT( AVG( IF ( HD.ID IS NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS PARCA_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(HD.ID IS NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS PARCA_GIRILMEMIS_30_ADET
						FROM 
							$this->hasarTable H
							LEFT JOIN HASAR_DETAIL HD ON H.ONAY_NO = HD.ONAY_NO		
							LEFT JOIN SIPARIS_DETAIL SD ON HD.ID = SD.YEDPAR_ID									
							INNER JOIN USERS U ON U.U_NAME  = H.USER_EKSPER	
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						WHERE 
							H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
							AND (IFNULL(U.FATURALI_KULLANICI, 0) = '1'  AND IFNULL(U.HKM_EKSPER, 0) = 0 AND IFNULL(U.OTOMOTIV,0)!=1)
							AND IFNULL(H.DOSYA_STATU,0)=0	
							AND H.DOSYA_NO NOT LIKE '%TEST%'							
							$kriter 
							$this->kullaniciKriter
					) AS T2	
					CROSS JOIN
					(
						SELECT 
							SUM(TN.NEDEN_ACIK_DOSYALAR) AS NEDEN_ACIK_DOSYALAR,
							FORMAT(SUM(TN.NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE) / SUM(TN.NEDEN_ACIK_DOSYALAR),0)AS NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE,
							SUM(TN.NEDEN_ACIK_DOSYALAR_30_ADET) AS NEDEN_ACIK_DOSYALAR_30_ADET
						FROM 
						(	SELECT
								COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL, H.ID, NULL)) AS NEDEN_ACIK_DOSYALAR, 
								FORMAT( AVG(  IF ( NA.ACIK_NOTU IS NOT NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS NEDEN_ACIK_DOSYALAR_30_ADET
							FROM
								$this->hasarTable H
							INNER JOIN USERS U ON U.U_NAME = H.USER_EKSPER
							INNER JOIN NEDEN_ACIK NA ON H.ID = NA.DOSYA_ID
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
							WHERE
								H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
								AND (IFNULL(U.FATURALI_KULLANICI, 0) = '1'  AND IFNULL(U.HKM_EKSPER, 0) = 0 AND IFNULL(U.OTOMOTIV,0)!=1)
								AND IFNULL(H.DOSYA_STATU,0)=0	
								AND H.DOSYA_NO NOT LIKE '%TEST%'	
								$kriter 
								$this->kullaniciKriter
						GROUP BY H.ID
						) AS TN 
					) AS T3	
				";
			//ECHO $sql;
			if (!($this->cdb->execute_sql($sql,$result,$error_msg))){return false;}
			$row = mysql_fetch_object($result);
			return $row;	
		}
		
		function teknikIncemeciBlok($ay_basi,$ay_sonu,$sorumlu,$brans,$servis_turu){
		
			if( ($this->kullaniciKontrol() == '2' || $this->hdsKullaniciKriter) ) { return false;}		
		
			if(($sorumlu!=NULL && $sorumlu!=-1)){ 
				$kriter .=  " AND DS.ID='$sorumlu'";
				
			} 
			
			if($brans!=NULL && $brans!=-1){ 
				$kriter .=  " AND H.SIGORTA_SEKLI='$brans'";
			}
			
			if($servis_turu==1){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1'";}
			if($servis_turu==2){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0'";}
			if($servis_turu==3){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==4){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==5){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==6){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==7){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==8){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='0'";}
		
			$sql = " 
					SELECT * FROM 
					(
						SELECT
							/*faturali blok*/
							COUNT(DISTINCT H.ID) AS TOPLAM_DOSYA_SAYISI,
							FORMAT(AVG( DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)),0) AS DOSYA_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS DOSYA_30_GECEN_SURE,
							
							COUNT(DISTINCT H.ID) AS TOPLAM_ADET,							
							
							COUNT(DISTINCT IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30,H.ID,NULL )) AS POLICE_FARK_DOSYA_SAY,
							FORMAT(AVG( IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30, DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT),NULL)),0) AS POLICE_FARK_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30, H.ID,NULL)) AS POLICE_FARK_30_GECEN_SURE,													
							
							COUNT(DISTINCT IF(H.SERVIS_ID IS NULL, H.ID, NULL)) AS SERVIS_GIRILMEMIS_DOSYA_ADET,
							FORMAT( AVG(  IF ( H.SERVIS_ID IS NULL , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS SERVIS_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SERVIS_ID IS NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS SERVIS_GIRILMEMIS_30_ADET,
							
							COUNT(DISTINCT IF(H.ON_RAPOR=1,H.ID,NULL)) AS ON_RAPO_ADET,
							FORMAT( AVG(  IF ( H.ON_RAPOR=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ON_RAPOR_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.ON_RAPOR=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ON_RAPOR_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.ON_RAPOR,0)=0,H.ID,NULL)) AS ON_RAPO_GONDERILMEYEN_ADET,
							FORMAT( AVG(  IF ( IFNULL(H.ON_RAPOR,0)=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ON_RAPO_GONDERILMEYEN_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.ON_RAPOR,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ON_RAPO_GONDERILMEYEN_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.PERT,0)=1,H.ID,NULL)) AS PERT_ADET,
							FORMAT( AVG( IF ( IFNULL(H.PERT,0)=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS PERT_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.PERT,0)=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS PERT_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0, H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA,
							FORMAT( AVG(  IF ( IFNULL(H.TAHMINI_HASAR,0)=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_30_ADET,

							COUNT(DISTINCT IF(H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1, H.ID, NULL)) AS SIPARIS_UYGUN_DOSYALAR,
							FORMAT( AVG(  IF (H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS SIPARIS_UYGUN_DOSYALAR_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS SIPARIS_UYGUN_DOSYALAR_30_ADET,

							FORMAT(SUM(H.SS_TAHMINI_HASAR),2) AS IHBAR_MUALLAK_TUTAR,
							FORMAT(SUM(H.TAHMINI_HASAR),2) AS EKSPER_MUALLAK_TUTAR,						

							COUNT(DISTINCT IF(H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0), H.ID, NULL)) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS,
							FORMAT( AVG(  IF (H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0), DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0) AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS_30_ADET,						

							COUNT(DISTINCT IF(H.RUCU =1, H.ID, NULL)) AS RUCU_ISARETLI,
							FORMAT( AVG(  IF ( H.RUCU =1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS RUCU_ISARETLI_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.RUCU =1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS RUCU_ISARETLI_30_ADET,
							
							COUNT(DISTINCT IF(H.FOTOVAR=0 , H.ID, NULL)) AS FOTO_EVRAK_YUKLENMEMIS_ADET,
							FORMAT( AVG( IF ( H.FOTOVAR=0 , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS FOTO_EVRAK_YUKLENMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.FOTOVAR=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS FOTO_EVRAK_YUKLENMEMIS_30_ADET
						FROM
							$this->hasarTable H							
							LEFT JOIN HASAR_MAGDUR_ARACLAR HMA ON H.ONAY_NO = HMA.ONAY_NO										
							LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME							
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						WHERE 
							H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
							AND IFNULL(U.TEKNIK_INC,0) =1
							AND IFNULL(H.DOSYA_STATU,0)=0	
							AND H.DOSYA_NO NOT LIKE '%TEST%'							
							$kriter
							$this->kullaniciKriter
					)
						AS T1 CROSS JOIN
					(
						SELECT 
							COUNT( DISTINCT 
									CASE 
									WHEN IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=1 THEN  H.ID
									WHEN IFNULL(HD.VERITABANINDA,0) <> 1 AND HD.ISLEM=1 THEN  H.ID
									END 
							) AS DEGISIM_ADET,						
							COUNT( DISTINCT
								CASE 
								WHEN HD.ISLEM=1 AND HD.MINI_ID=0 AND ((IFNULL(HD.SOKTAK,0) + IFNULL(HD.BOYA_TUTAR,0) + IFNULL(HD.TAMIR,0))>0) THEN H.ID
								WHEN IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=2 THEN  H.ID
								WHEN IFNULL(HD.VERITABANINDA,0) <> 1 AND HD.ISLEM=2 THEN  H.ID
								WHEN HD.ISLEM=3 THEN H.ID
								END 
							) AS ONARIM_ADET,
							FORMAT( AVG( IF ( HD.ISLEM = 1 , DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT )  ,NULL)),0) AS DEGISIM_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(HD.ISLEM =1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS DEGISIM_30_ADET,
							
							FORMAT( AVG( IF ( HD.ISLEM NOT IN (1) ,  DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ONARIM_ORT_GECEN_SURE,		
							COUNT(DISTINCT IF(HD.ISLEM NOT IN (1) AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ONARIM_30_ADET,
							
							COUNT(DISTINCT IF(HD.ID IS NULL, H.ID,NULL)) AS PARCA_GIRILMEMIS_DOSYA_ADET,
							FORMAT( AVG( IF ( HD.ID IS NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS PARCA_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(HD.ID IS NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS PARCA_GIRILMEMIS_30_ADET
						FROM 
							$this->hasarTable H
							LEFT JOIN HASAR_DETAIL HD ON H.ONAY_NO = HD.ONAY_NO		
							LEFT JOIN SIPARIS_DETAIL SD ON HD.ID = SD.YEDPAR_ID									
							INNER JOIN USERS U ON U.U_NAME  = H.USER_EKSPER	
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						WHERE 
							H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
							AND IFNULL(U.TEKNIK_INC,0) =1
							AND IFNULL(H.DOSYA_STATU,0)=0	
							AND H.DOSYA_NO NOT LIKE '%TEST%'							
							$kriter 
							$this->kullaniciKriter
					) AS T2	
					CROSS JOIN
					(
						SELECT 
							SUM(TN.NEDEN_ACIK_DOSYALAR) AS NEDEN_ACIK_DOSYALAR,
							FORMAT(SUM(TN.NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE) / SUM(TN.NEDEN_ACIK_DOSYALAR),0)AS NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE,
							SUM(TN.NEDEN_ACIK_DOSYALAR_30_ADET) AS NEDEN_ACIK_DOSYALAR_30_ADET
						FROM 
						(	SELECT
								COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL, H.ID, NULL)) AS NEDEN_ACIK_DOSYALAR, 
								FORMAT( AVG(  IF ( NA.ACIK_NOTU IS NOT NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS NEDEN_ACIK_DOSYALAR_30_ADET
							FROM
								$this->hasarTable H
							INNER JOIN USERS U ON U.U_NAME = H.USER_EKSPER
							INNER JOIN NEDEN_ACIK NA ON H.ID = NA.DOSYA_ID
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
							WHERE
								H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
								AND IFNULL(U.TEKNIK_INC,0) =1
								AND IFNULL(H.DOSYA_STATU,0)=0	
								AND H.DOSYA_NO NOT LIKE '%TEST%'	
								$kriter 
								$this->kullaniciKriter
						GROUP BY H.ID
						) AS TN 
					) AS T3	
				";
			//ECHO $sql;
			if (!($this->cdb->execute_sql($sql,$result,$error_msg))){return false;}
			$row = mysql_fetch_object($result);
			return $row;	
		}
		
		function camBlok($ay_basi,$ay_sonu,$sorumlu,$brans,$servis_turu){
		
			if($this->kullaniciKontrol() == '2' || $this->hdsKullaniciKriter)  { return false;}		
		
			if(($sorumlu!=NULL && $sorumlu!=-1)){ 
				$kriter .=  " AND DS.ID='$sorumlu'";
				
			}		
			
			if($brans!=NULL && $brans!=-1){ 
				$kriter .=  " AND H.SIGORTA_SEKLI='$brans'";
			}
			
			if($servis_turu==1){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1'";}
			if($servis_turu==2){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0'";}
			if($servis_turu==3){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==4){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==5){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==6){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==7){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==8){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='0'";}
		
			$sql = " 
					SELECT * FROM 
					(
						SELECT
							/*cam blok*/
							COUNT(DISTINCT H.ID) AS TOPLAM_DOSYA_SAYISI,
							FORMAT(AVG( DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)),0) AS DOSYA_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS DOSYA_30_GECEN_SURE,
							
							COUNT(DISTINCT H.ID) AS TOPLAM_ADET,							
							
							COUNT(DISTINCT IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30,H.ID,NULL )) AS POLICE_FARK_DOSYA_SAY,
							FORMAT(AVG( IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30, DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT),NULL)),0) AS POLICE_FARK_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30, H.ID,NULL)) AS POLICE_FARK_30_GECEN_SURE,													
							
							COUNT(DISTINCT IF(H.SERVIS_ID IS NULL, H.ID, NULL)) AS SERVIS_GIRILMEMIS_DOSYA_ADET,
							FORMAT( AVG(  IF ( H.SERVIS_ID IS NULL , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS SERVIS_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SERVIS_ID IS NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS SERVIS_GIRILMEMIS_30_ADET,
							
							COUNT(DISTINCT IF(H.ON_RAPOR=1,H.ID,NULL)) AS ON_RAPO_ADET,
							FORMAT( AVG(  IF ( H.ON_RAPOR=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ON_RAPOR_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.ON_RAPOR=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ON_RAPOR_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.ON_RAPOR,0)=0,H.ID,NULL)) AS ON_RAPO_GONDERILMEYEN_ADET,
							FORMAT( AVG(  IF ( IFNULL(H.ON_RAPOR,0)=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ON_RAPO_GONDERILMEYEN_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.ON_RAPOR,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ON_RAPO_GONDERILMEYEN_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.PERT,0)=1,H.ID,NULL)) AS PERT_ADET,
							FORMAT( AVG( IF ( IFNULL(H.PERT,0)=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS PERT_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.PERT,0)=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS PERT_30_ADET,
							
							COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0, H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA,
							FORMAT( AVG(  IF ( IFNULL(H.TAHMINI_HASAR,0)=0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS MULLAK_GIRISI_YAPILMAYAN_DOSYA_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(IFNULL(H.TAHMINI_HASAR,0)=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS MULLAK_GIRISI_YAPILMAYAN_30_ADET,

							COUNT(DISTINCT IF(H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1, H.ID, NULL)) AS SIPARIS_UYGUN_DOSYALAR,
							FORMAT( AVG(  IF (H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS SIPARIS_UYGUN_DOSYALAR_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SIPARIS_UYGUN=1 AND H.SIPARIS_VAR=1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS SIPARIS_UYGUN_DOSYALAR_30_ADET,

							FORMAT(SUM(H.SS_TAHMINI_HASAR),2) AS IHBAR_MUALLAK_TUTAR,
							FORMAT(SUM(H.TAHMINI_HASAR),2) AS EKSPER_MUALLAK_TUTAR,						

							COUNT(DISTINCT IF(H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0), H.ID, NULL)) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS,
							FORMAT( AVG(  IF (H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0), DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.SIGORTA_SEKLI=1 AND (IFNULL(HMA.MARKA_ID,0) =0 OR IFNULL(HMA.MODEL_KODU,0)=0) AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS MAGDUR_ARAC_BILGILERI_GIRILMEMIS_30_ADET,						

							COUNT(DISTINCT IF(H.RUCU =1, H.ID, NULL)) AS RUCU_ISARETLI,
							FORMAT( AVG(  IF ( H.RUCU =1, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS RUCU_ISARETLI_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.RUCU =1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS RUCU_ISARETLI_30_ADET,

							COUNT(DISTINCT IF(H.FOTOVAR=0 , H.ID, NULL)) AS FOTO_EVRAK_YUKLENMEMIS_ADET,
							FORMAT( AVG( IF ( H.FOTOVAR=0 , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS FOTO_EVRAK_YUKLENMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(H.FOTOVAR=0 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS FOTO_EVRAK_YUKLENMEMIS_30_ADET
						FROM
							$this->hasarTable H							
							LEFT JOIN HASAR_MAGDUR_ARACLAR HMA ON H.ONAY_NO = HMA.ONAY_NO										
							LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME							
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						WHERE 
							H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
							AND U.FATURALI_KULLANICI=1		
							AND IFNULL(U.OTOMOTIV,0)=1
							AND IFNULL(U.HKM_EKSPER,0) =0
							AND IFNULL(H.DOSYA_STATU,0)=0	
							AND H.DOSYA_NO NOT LIKE '%TEST%'							
							".$kriter."
							".$this->kullaniciKriter."
					)
						AS T1 CROSS JOIN
					(
						SELECT 
							COUNT( DISTINCT 
									CASE 
									WHEN IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=1 THEN  H.ID
									WHEN IFNULL(HD.VERITABANINDA,0) <> 1 AND HD.ISLEM=1 THEN  H.ID
									END 
							) AS DEGISIM_ADET,						
							COUNT( DISTINCT
								CASE 
								WHEN HD.ISLEM=1 AND HD.MINI_ID=0 AND ((IFNULL(HD.SOKTAK,0) + IFNULL(HD.BOYA_TUTAR,0) + IFNULL(HD.TAMIR,0))>0) THEN H.ID
								WHEN IFNULL(HD.VERITABANINDA,0) =  1 AND HD.ISLEM=2 THEN  H.ID
								WHEN IFNULL(HD.VERITABANINDA,0) <> 1 AND HD.ISLEM=2 THEN  H.ID
								WHEN HD.ISLEM=3 THEN H.ID
								END 
							) AS ONARIM_ADET,
							FORMAT( AVG( IF ( HD.ISLEM = 1 , DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT )  ,NULL)),0) AS DEGISIM_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(HD.ISLEM =1 AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS DEGISIM_30_ADET,
							
							FORMAT( AVG( IF ( HD.ISLEM NOT IN (1) ,  DATEDIFF( NOW(), HD.KAYIT_TARIH_SAAT ) ,NULL)),0) AS ONARIM_ORT_GECEN_SURE,		
							COUNT(DISTINCT IF(HD.ISLEM NOT IN (1) AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS ONARIM_30_ADET,
							
							COUNT(DISTINCT IF(HD.ID IS NULL, H.ID,NULL)) AS PARCA_GIRILMEMIS_DOSYA_ADET,
							FORMAT( AVG( IF ( HD.ID IS NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS PARCA_GIRILMEMIS_ORT_GECEN_SURE,
							COUNT(DISTINCT IF(HD.ID IS NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS PARCA_GIRILMEMIS_30_ADET
						FROM 
							$this->hasarTable H
							LEFT JOIN HASAR_DETAIL HD ON H.ONAY_NO = HD.ONAY_NO		
							LEFT JOIN SIPARIS_DETAIL SD ON HD.ID = SD.YEDPAR_ID									
							INNER JOIN USERS U ON U.U_NAME  = H.USER_EKSPER	
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						WHERE 
							H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
							AND U.FATURALI_KULLANICI=1		
							AND IFNULL(U.OTOMOTIV,0)=1
							AND IFNULL(U.HKM_EKSPER,0) =0
							AND IFNULL(H.DOSYA_STATU,0)=0	
							AND H.DOSYA_NO NOT LIKE '%TEST%'							
							".$kriter."
							".$this->kullaniciKriter."
					) AS T2	
					CROSS JOIN
					(
						SELECT 
							SUM(TN.NEDEN_ACIK_DOSYALAR) AS NEDEN_ACIK_DOSYALAR,
							FORMAT(SUM(TN.NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE) / SUM(TN.NEDEN_ACIK_DOSYALAR),0)AS NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE,
							SUM(TN.NEDEN_ACIK_DOSYALAR_30_ADET) AS NEDEN_ACIK_DOSYALAR_30_ADET
						FROM 
						(	SELECT
								COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL, H.ID, NULL)) AS NEDEN_ACIK_DOSYALAR, 
								FORMAT( AVG(  IF ( NA.ACIK_NOTU IS NOT NULL, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT ) ,NULL)),0) AS NEDEN_ACIK_DOSYALAR_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(NA.ACIK_NOTU IS NOT NULL AND DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)>30,H.ID,NULL)) AS NEDEN_ACIK_DOSYALAR_30_ADET
							FROM
								$this->hasarTable H
							INNER JOIN USERS U ON U.U_NAME = H.USER_EKSPER
							INNER JOIN NEDEN_ACIK NA ON H.ID = NA.DOSYA_ID
							LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
							WHERE
								H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
								AND U.FATURALI_KULLANICI=1		
								AND IFNULL(U.OTOMOTIV,0)=1
								AND IFNULL(U.HKM_EKSPER,0) =0
								AND IFNULL(H.DOSYA_STATU,0)=0	
								AND H.DOSYA_NO NOT LIKE '%TEST%'	
								".$kriter."
								".$this->kullaniciKriter."
						GROUP BY H.ID
						) AS TN 
					) AS T3						
				";
				//ECHO $sql; die;
			if (!($this->cdb->execute_sql($sql,$result,$error_msg))){return false;}
			$row = mysql_fetch_object($result);
			return $row;	
		}
		
		function tedarikBlok($ay_basi,$ay_sonu,$sorumlu,$brans,$servis_turu){
		
			if( ($this->kullaniciKontrol() == '2' || $this->hdsKullaniciKriter) ) { return false;}		
		
			if(($sorumlu!=NULL && $sorumlu!=-1)){ 
				$kriter .=  " AND DS.ID='$sorumlu'";
				
			}
			
			if($brans!=NULL && $brans!=-1){ 
				$kriter .=  " AND H.SIGORTA_SEKLI='$brans'";
			}
			
			if($servis_turu==1){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1'";}
			if($servis_turu==2){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0'";}
			if($servis_turu==3){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==4){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==5){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==6){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==7){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==8){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='0'";}
		
			$sql = " 
					SELECT * FROM 
						(
							SELECT 
								COUNT(DISTINCT IF(H.DOSYA_STATU=0, H.ID, NULL)) AS TOPLAM_DOSYA_SAYISI,
								FORMAT( AVG( DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT)),0) AS DOSYA_ORT_GECEN_SURE,						
								COUNT(DISTINCT IF ( DATEDIFF(NOW(), H.KAYIT_TARIH_SAAT)> 30, H.ID,NULL)) DOSYA_30_GECEN_SURE
							FROM 
								$this->hasarTable H
								LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME
								LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
							WHERE
									H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
									AND H.DOSYA_STATU = 0
									AND H.DOSYA_NO NOT LIKE '%TEST%'
									AND H.SIPARIS_UYGUN=1
									AND H.SIPARIS_VAR = 1
									$kriter
									$this->kullaniciKriter
						) AS T1
						CROSS JOIN
						(
							SELECT 
								COUNT(DISTINCT IF(H.DOSYA_STATU=0, S.ID, NULL)) AS TOPLAM_SIPARIS_SAYISI,
								FORMAT( AVG( IF ( H.DOSYA_STATU = 0 AND S.TARIH_TEDARIKCI IS NULL, DATEDIFF(NOW(), S.TARIH_SIPARIS), DATEDIFF(S.TARIH_TEDARIKCI, S.TARIH_SIPARIS))),0) AS SIPARIS_ORT_GECEN_SURE,						
								COUNT(DISTINCT IF ( H.DOSYA_STATU = 0 AND ((S.TARIH_TEDARIKCI IS NULL AND DATEDIFF(NOW(), S.TARIH_SIPARIS)> 30) OR (S.TARIH_TEDARIKCI IS NULL AND DATEDIFF(S.TARIH_TEDARIKCI, S.TARIH_SIPARIS)> 30)), S.ID,NULL)) SIPARIS_30_GECEN_SURE
							FROM 
									SIPARIS S 
									LEFT JOIN $this->hasarTable H ON H.ID = S.DOSYA_ID
									LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME
									LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
							WHERE	
										H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
										AND H.DOSYA_STATU = 0
										AND H.DOSYA_NO NOT LIKE '%TEST%'
										AND H.SIPARIS_UYGUN=1
										AND H.SIPARIS_VAR = 1
										$kriter
										$this->kullaniciKriter
						) AS T2
						CROSS JOIN
						(
							SELECT 								
								COUNT(DISTINCT IF( S.STATUS = 1,S.ID,NULL)) AS STOK_KONTROL_SAY,
								FORMAT( AVG( IF ( S.STATUS = 1 ,  DATEDIFF( NOW(), S.TARIH_SIPARIS ) ,NULL)),0) AS STOK_KONTROL_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(S.STATUS = 1 AND DATEDIFF(NOW(),S.TARIH_SIPARIS)>30,S.ID,NULL)) AS STOK_KONTROL_30_ADET,
								
								COUNT(DISTINCT IF(SD.STATUS = 1 AND (S.SEVK_TARIHI IS NULL OR S.SEVK_TARIHI = '0000-00-00 00:00:00') AND S.TARIH_TEDARIKCI >= '2019-01-01 00:00:00', S.ID, NULL)) AS SEVK_EDILECEK_SAY,
								FORMAT( AVG( IF ( SD.STATUS = 1 AND (S.SEVK_TARIHI IS NULL OR S.SEVK_TARIHI = '0000-00-00 00:00:00') AND S.TARIH_TEDARIKCI >= '2019-01-01 00:00:00', DATEDIFF( NOW(), S.TARIH_TEDARIKCI ) ,NULL)),0) AS SEVK_EDILECEK_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(SD.STATUS = 1 AND (S.SEVK_TARIHI IS NULL OR S.SEVK_TARIHI = '0000-00-00 00:00:00') AND S.TARIH_TEDARIKCI >= '2019-01-01 00:00:00' AND DATEDIFF(NOW(),S.TARIH_TEDARIKCI)>30,S.ID,NULL)) AS SEVK_EDILECEK_30_ADET,
								
								COUNT(DISTINCT IF(SD.STATUS = 1 AND (S.TESLIM_TARIHI IS NULL OR S.TESLIM_TARIHI = '0000-00-00 00:00:00') AND S.TARIH_TEDARIKCI >= '2019-01-01 00:00:00', S.ID, NULL)) AS TESLIM_EDILECEK_SAY,
								FORMAT( AVG( IF ( SD.STATUS = 1 AND (S.TESLIM_TARIHI IS NULL OR S.TESLIM_TARIHI = '0000-00-00 00:00:00') AND S.TARIH_TEDARIKCI >= '2019-01-01 00:00:00', DATEDIFF( NOW(), S.TARIH_TEDARIKCI ) ,NULL)),0) AS TESLIM_EDILECEK_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(SD.STATUS = 1 AND (S.TESLIM_TARIHI IS NULL OR S.TESLIM_TARIHI = '0000-00-00 00:00:00') AND S.TARIH_TEDARIKCI >= '2019-01-01 00:00:00' AND DATEDIFF(NOW(),S.TARIH_TEDARIKCI)>30,S.ID,NULL)) AS TESLIM_EDILECEK_30_ADET,
								
								COUNT(DISTINCT IF(SD.STATUS = 1 AND SUP.ID IS NULL AND S.TARIH_TEDARIKCI>='2019-01-01 01:00:00', S.ID, NULL) ) AS FATURA_SAY,														
								FORMAT( AVG( IF ( SD.STATUS = 1 AND SUP.ID IS NULL AND S.TARIH_TEDARIKCI>='2019-01-01 01:00:00' AND H.DOSYA_STATU = 0 ,  DATEDIFF( NOW(), S.TARIH_TEDARIKCI ) ,NULL)),0) AS FATURA_GECEN_ORT_SURE,								
								COUNT(DISTINCT IF(SD.STATUS = 1 AND SUP.ID IS NULL AND S.TARIH_TEDARIKCI>='2019-01-01 01:00:00' AND H.DOSYA_STATU = 0 AND DATEDIFF(NOW(),S.TARIH_TEDARIKCI)>30,S.ID,NULL)) AS FATURA_30_ADET,
								
								".( ($this->companyId == 75) ? " 
									COUNT(DISTINCT SD.ERTELEME_SEBEP=1,1,NULL) AS YURT_DISI_SAY,	 
									FORMAT( AVG( DATEDIFF( NOW(), S.TARIH_TEDARIKCI)),0) AS YURT_DISI_ORT_GECEN_SURE,						
									COUNT(DISTINCT IF ( DATEDIFF(NOW(), S.TARIH_TEDARIKCI)> 30, H.ID,NULL)) YURT_DISI_30_GECEN_SURE,
								" : "" )."																
								1
							FROM 
									SIPARIS S 
									LEFT JOIN $this->hasarTable H ON H.ID = S.DOSYA_ID
									LEFT JOIN SIPARIS_USERS SU ON SU.ID = S.TEDARIKCI_ID														
									LEFT JOIN SERVIS SR ON S.SERVIS_ID = SR.ID
									LEFT JOIN (
										SELECT SD.ID,SD.SIPARIS_ID,".( ($this->companyId == 75) ? " SD.ERTELEME_SEBEP, " : "" )."SD.STATUS
												FROM 
												SIPARIS_DETAIL SD 
												INNER JOIN SIPARIS S ON S.ID = SD.SIPARIS_ID
												INNER JOIN $this->hasarTable H ON H.ID = S.DOSYA_ID
												LEFT JOIN USERS U ON U.U_NAME = H.USER_EKSPER
												LEFT JOIN SIPARIS_UPLOAD SUP ON SUP.SIPARIS_ID = S.ID AND SUP.ID IS NULL
												LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
												WHERE 
														H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
														AND H.DOSYA_STATU = 0
														AND H.DOSYA_NO NOT LIKE '%TEST%'
														AND H.SIPARIS_UYGUN=1
														AND H.SIPARIS_VAR = 1
														AND SD.STATUS=1
														$kriter
														$this->kullaniciKriter														
													GROUP BY S.ID
									) SD ON S.ID = SD.SIPARIS_ID
									LEFT JOIN ILLER ON ILLER.ID = SR.IL														
									LEFT JOIN USERS U ON U.U_NAME = H.USER_EKSPER
									LEFT JOIN SIPARIS_UPLOAD SUP ON SUP.SIPARIS_ID = S.ID										
									LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
							WHERE
								H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
								AND H.DOSYA_STATU = 0
								AND H.DOSYA_NO NOT LIKE '%TEST%'
								AND H.SIPARIS_UYGUN=1
								AND H.SIPARIS_VAR = 1
								$kriter
								$this->kullaniciKriter
						) AS T3 
						CROSS JOIN (
							SELECT
								SUM(TMP.EKSPER_TALEP_SAY) AS EKSPER_TALEP_SAY,
								SUM(TMP.EKSPER_TALEP_PARCA_SAY) AS EKSPER_TALEP_PARCA_SAY,
								FORMAT(
									SUM(
										EKSPER_TALEP_ORT_GECEN_SURE
									) / SUM(TMP.EKSPER_TALEP_SAY),
									0
								) AS EKSPER_TALEP_ORT_GECEN_SURE,
								TMP.EKSPER_TALEP_30_ADET
							FROM
								(
									SELECT
										COUNT(DISTINCT KT.DOSYA_ID) AS EKSPER_TALEP_SAY,
										COUNT(DISTINCT KT.ID) AS EKSPER_TALEP_PARCA_SAY,
										FORMAT( AVG( IF ( KT.YP_KOD IS NULL AND KT.TARIH_TEDARIKCI IS NULL, DATEDIFF(NOW(), KT.TARIH_EKSPER), NULL ) ), 0) AS EKSPER_TALEP_ORT_GECEN_SURE,
										COUNT( DISTINCT IF (KT.YP_KOD IS NULL AND KT.TARIH_TEDARIKCI IS NULL AND DATEDIFF(NOW(), KT.TARIH_EKSPER) > 30, KT.ID, NULL )) AS EKSPER_TALEP_30_ADET
									FROM
										EKS_YPKOD_TALEP KT
									INNER JOIN $this->hasarTable H ON H.ID = KT.DOSYA_ID
									LEFT JOIN USERS U ON U.U_NAME = H.USER_EKSPER
									LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
									WHERE
										H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
										AND H.DOSYA_STATU = 0
										AND H.DOSYA_NO NOT LIKE '%TEST%'
										AND H.SIPARIS_UYGUN = 1
										#AND H.SIPARIS_VAR = 1
										AND KT.YP_KOD IS NULL
										AND KT.TARIH_TEDARIKCI IS NULL
										AND KT.DOSYA_ID IS NOT NULL
										$kriter
										$this->kullaniciKriter
									GROUP BY
										KT.DOSYA_ID
								) AS TMP
						) AS T4
						CROSS JOIN
						(
							SELECT 
								COUNT(DISTINCT IF(SD.STATUS = 4 AND (SD.IADE_ONAY = 0 OR SD.IADE_ONAY IS NULL), SD.ID, NULL)) AS IADE_SAY,
								COUNT(DISTINCT IF(SD.STATUS = 4 AND SD.IADE_ONAY = 1 AND (UNIX_TIMESTAMP(NOW())-UNIX_TIMESTAMP(SD.TARIH_IADE))<2592000, SD.ID, NULL)) AS ONAYLANMIS_IADE_SAY,	

								FORMAT( AVG( IF ( SD.STATUS = 4 AND (SD.IADE_ONAY = 0 OR SD.IADE_ONAY IS NULL) ,  DATEDIFF( NOW(),SD.TARIH_IADE) ,NULL)),0) AS IADE_ORT_GECEN_SURE,
								FORMAT( AVG( IF ( SD.STATUS = 4 AND SD.IADE_ONAY = 1 AND (UNIX_TIMESTAMP(NOW())-UNIX_TIMESTAMP(SD.TARIH_IADE))<2592000,  DATEDIFF( NOW(),SD.TARIH_IADE ) ,NULL)),0) AS ONAYLANMAMIS_ORT_GECEN_SURE,

								COUNT(DISTINCT IF(SD.STATUS = 4 AND (SD.IADE_ONAY = 0 OR SD.IADE_ONAY IS NULL) AND DATEDIFF(NOW(),SD.TARIH_IADE)>30,SD.ID,NULL)) AS IADE_30_ADET,
								COUNT(DISTINCT IF(SD.STATUS = 4 AND SD.IADE_ONAY = 1 AND (UNIX_TIMESTAMP(NOW())-UNIX_TIMESTAMP(SD.TARIH_IADE))<2592000 AND DATEDIFF(NOW(),SD.TARIH_IADE)>30,S.ID,NULL)) AS ONAYLANMIS_IADE_30_ADET
							FROM 
									SIPARIS S 
									INNER JOIN SIPARIS_DETAIL SD ON S.ID = SD.SIPARIS_ID
									LEFT JOIN $this->hasarTable H ON H.ID = S.DOSYA_ID
									LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME
									LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
							WHERE	
										H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
										AND H.DOSYA_STATU = 0
										AND H.DOSYA_NO NOT LIKE '%TEST%'
										AND H.SIPARIS_UYGUN=1
										AND H.SIPARIS_VAR = 1										
										$kriter
										$this->kullaniciKriter							
						) AS T5
						".( ($this->companyId == 48 || $this->companyId == 70 || $this->companyId == 75 || $this->companyId == 80) ? "
						CROSS JOIN
						(
							SELECT 
								COUNT(DISTINCT IF(S2.STATUS=1,S2.ID,NULL)) AS SAY_YENI_IHALE,
								FORMAT( AVG( IF ( S2.STATUS = 1 ,  DATEDIFF( NOW(), S2.TARIH_SIPARIS ) ,NULL)),0) AS SAY_YENI_IHALE_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(S2.STATUS = 1 AND DATEDIFF(NOW(),S2.TARIH_SIPARIS)>30,S2.ID,NULL)) AS SAY_YENI_IHALE_30_ADET,
								COUNT(DISTINCT IF(S2.STATUS=2,SD2.SIPARIS_ID,NULL)) AS SAY_CEVAPLANAN_IHALE,
								FORMAT( AVG( IF ( S2.STATUS = 2 ,  DATEDIFF( NOW(), S2.TARIH_TEDARIKCI) ,NULL)),0) AS SAY_CEVAPLANAN_IHALE_ORT_GECEN_SURE,
								COUNT(DISTINCT IF(S2.STATUS = 2 AND DATEDIFF(NOW(), S2.TARIH_TEDARIKCI)>30,S2.ID,NULL)) AS SAY_CEVAPLANAN_IHALE_IHALE_30_ADET
							FROM
								$this->hasarTable H 
								LEFT JOIN SIPARIS2 S2 ON H.ID = S2.DOSYA_ID 
								LEFT JOIN SIPARIS_DETAIL2 SD2 ON SD2.SIPARIS_ID = S2.ID 
								LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME
								LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
							WHERE 
								H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
								AND H.DOSYA_STATU = 0
								AND H.DOSYA_NO NOT LIKE '%TEST%'
								AND H.SIPARIS_UYGUN=1
								AND H.SIPARIS_VAR = 1								
								AND S2.IHALE_BITTI <> 1	
								$kriter
								$this->kullaniciKriter
						) AS T6
						" : "" )."
				";	
				//ECHO $sql;
			if (!($this->cdb->execute_sql($sql,$result,$error_msg))){return false;}
			$row = mysql_fetch_object($result);
			return $row;	
		
		}
		
		
		function mobilOnarimBlok($ay_basi,$ay_sonu,$sorumlu,$brans,$servis_turu){
		
			if($this->kullaniciKontrol() == '2' || $this->hdsKullaniciKriter) { return false;}		
		
			if(($sorumlu!=NULL && $sorumlu!=-1)){ 
				$kriter .=  " AND DS.ID='$sorumlu'";
				
			}
			
			if($brans!=NULL && $brans!=-1){ 
				$kriter .=  " AND H.SIGORTA_SEKLI='$brans'";
			}
			
			if($servis_turu==1){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1'";}
			if($servis_turu==2){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0'";}
			if($servis_turu==3){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==4){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==5){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==6){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==7){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==8){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='0'";}
		
			$sql = " 
					SELECT 
						
						SUM(T.MO_KONU_DOSYA_ADET) AS MO_KONU_DOSYA_ADET,
						SUM(T.MO_KONU_PARCA_ADET) AS MO_KONU_PARCA_ADET,
						FORMAT(AVG(T.MO_FARK_KONU_DOSYA),0) AS MO_KONU_ORT_SURE,
						COUNT(DISTINCT IF(T.MO_FARK_KONU_DOSYA>30,T.H_ID,NULL)) AS MO_KONU_30_DOSYA_ADET,

						
						SUM(T.POLICE_FARK_DOSYA_SAY) AS POLICE_FARK_DOSYA_SAY,	
						FORMAT(AVG(IF(DATEDIFF(T.HASAR_TARIHI,T.SB_POLICE_BAS)<30,DATEDIFF(NOW(),T.H_KAYIT_TARIH_SAAT),NULL)),0) AS POLICE_FARK_ORT_GECEN_SURE, 
						COUNT(DISTINCT IF(DATEDIFF(T.HASAR_TARIHI,T.SB_POLICE_BAS)<30 AND DATEDIFF(NOW(),T.H_KAYIT_TARIH_SAAT)>30, T.H_ID,NULL)) AS POLICE_FARK_30_GECEN_SURE, 

						
						SUM(T.MO_GONDERILEN_DOSYA_ADET) AS MO_GONDERILEN_DOSYA_ADET,
						SUM(T.MO_GONDERILEN_PARCA_ADET) AS MO_GONDERILEN_PARCA_ADET,
						FORMAT(AVG(T.MO_FARK_GONDERILEN),0) AS MO_GONDERILEN_ORT_SURE, 
						COUNT(DISTINCT IF(T.MO_FARK_GONDERILEN>30,T.H_ID,NULL)) AS MO_GONDERILEN_30_DOSYA_ADET,
						
						
						SUM(T.MO_CEVAP_BEKLEYEN_DOSYA_ADET) AS MO_CEVAP_BEKLEYEN_DOSYA_ADET,
						SUM(T.MO_CEVAP_BEKLEYEN_PARCA_ADET) AS MO_CEVAP_BEKLEYEN_PARCA_ADET,
						FORMAT(AVG(T.MO_FARK_CEVAP_BEKLEYEN),0) AS MO_CEVAP_BEKLEYEN_ORT_SURE, 
						COUNT(DISTINCT IF(T.MO_FARK_CEVAP_BEKLEYEN>30,T.H_ID,NULL)) AS MO_CEVAP_BEKLEYEN_30_DOSYA_ADET,

						
						SUM(T.MO_GONDERILMEYEN_DOSYA_ADET) AS MO_GONDERILMEYEN_DOSYA_ADET,
						SUM(T.MO_GONDERILMEYEN_PARCA_ADET) AS MO_GONDERILMEYEN_PARCA_ADET,
						FORMAT(AVG(T.MO_FARK_GONDERILMEYEN),0) AS MO_GONDERILMEYEN_ORT_SURE, 
						COUNT(DISTINCT IF(T.MO_FARK_GONDERILMEYEN>30,T.H_ID,NULL)) AS MO_GONDERILMEYEN_30_DOSYA_ADET,

						
						SUM(T.MO_MODUL_IPTAL_DOSYA_ADET) AS MO_MODUL_IPTAL_DOSYA_ADET,
						SUM(T.MO_MODUL_IPTAL_PARCA_ADET) AS MO_MODUL_IPTAL_PARCA_ADET,
						FORMAT(AVG(T.MO_FARK_MODUL_IPTAL),0) AS MO_MODUL_IPTAL_ORT_SURE, 
						COUNT(DISTINCT IF(T.MO_FARK_MODUL_IPTAL>30,T.H_ID,NULL)) AS MO_MODUL_IPTAL_30_DOSYA_ADET,

						
						SUM(T.MO_ONARILAN_DOSYA_ADET) AS MO_ONARILAN_DOSYA_ADET,
						SUM(T.MO_ONARILAN_PARCA_ADET) AS MO_ONARILAN_PARCA_ADET,
						FORMAT(AVG(T.MO_FARK_ONARILAN),0) AS MO_ONARILAN_ORT_SURE, 
						COUNT(DISTINCT IF(T.MO_FARK_ONARILAN>30,T.H_ID,NULL)) AS MO_ONARILAN_30_DOSYA_ADET,

						
						SUM(T.MO_ONARILAMAYAN_DOSYA_ADET) AS MO_ONARILAMAYAN_DOSYA_ADET,
						SUM(T.MO_ONARILAMAYAN_PARCA_ADET) AS MO_ONARILAMAYAN_PARCA_ADET,
						FORMAT(AVG(T.MO_FARK_ONARILAMAYAN),0) AS MO_ONARILAMAYAN_ORT_SURE, 
						COUNT(DISTINCT IF(T.MO_FARK_ONARILAMAYAN>30,T.H_ID,NULL)) AS MO_ONARILAMAYAN_30_DOSYA_ADET,	

						
						SUM(T.MO_DEGERLENDIRILMEYEN_DOSYA_ADET) AS MO_DEGERLENDIRILMEYEN_DOSYA_ADET,
						SUM(T.MO_DEGERLENDIRILMEYEN_PARCA_ADET) AS MO_DEGERLENDIRILMEYEN_PARCA_ADET,
						FORMAT(AVG(T.MO_FARK_DEGERLENDIRILMEYEN),0) AS MO_DEGERLENDIRILMEYEN_ORT_SURE, 
						COUNT(DISTINCT IF(T.MO_FARK_DEGERLENDIRILMEYEN>30,T.H_ID,NULL)) AS MO_DEGERLENDIRILMEYEN_30_DOSYA_ADET,

						".( ($this->companyId == 19) ? "
						#ihale DOSYA
						SUM(T.MO_IHALE_DOSYA_ADET) AS MO_IHALE_DOSYA_ADET,
						SUM(T.MO_IHALE_PARCA_ADET) AS MO_IHALE_PARCA_ADET,
						FORMAT(AVG(T.MO_FARK_IHALE_PARCA),0) AS MO_DEGERLENDIRILMEYEN_ORT_SURE, 
						COUNT(DISTINCT IF(T.MO_FARK_IHALE_PARCA>30,T.H_ID,NULL)) AS MO_DEGERLENDIRILMEYEN_30_DOSYA_ADET,
						" : "" )."
						1
					FROM (
						SELECT 
								H.ID AS H_ID,
								H.KAYIT_TARIH_SAAT AS H_KAYIT_TARIH_SAAT,
								H.HASAR_TARIHI,
								H.SB_POLICE_BAS,						
								/*KONU DOSYA*/
								COUNT(DISTINCT IF(((HD.ISLEM=1 AND IFNULL(AD.ID,0)=0) OR (IFNULL(AD.ID,0)>0)),H.ID,NULL)) AS MO_KONU_DOSYA_ADET, 
								COUNT(DISTINCT IF(((HD.ISLEM=1 AND IFNULL(AD.ID,0)=0) OR (IFNULL(AD.ID,0)>0)),HD.ID,NULL)) AS MO_KONU_PARCA_ADET,
								IF(((HD.ISLEM=1 AND IFNULL(AD.ID,0)=0) OR (IFNULL(AD.ID,0)>0)),DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT),NULL) AS MO_FARK_KONU_DOSYA,								
								
								/*POLICE DOSYA*/
								COUNT(DISTINCT IF(DATEDIFF(H.HASAR_TARIHI,H.SB_POLICE_BAS)<30,H.ID,NULL )) AS POLICE_FARK_DOSYA_SAY, 

								/*GONDERILEN DOSYA*/
								COUNT(DISTINCT IF(IFNULL(AD.ID,0)>0,H.ID,NULL)) AS MO_GONDERILEN_DOSYA_ADET, 
								COUNT(DISTINCT IF(IFNULL(AD.ID,0)>0,AD.ID,NULL)) AS MO_GONDERILEN_PARCA_ADET,
								IF(IFNULL(AD.ID,0)>0, DATEDIFF(MAX(IFNULL(AD.MODIFIED_AT,NOW())),MIN(AD.CREATED_AT)), NULL) AS MO_FARK_GONDERILEN,

								/*CEVAP_BEKLEYEN DOSYA*/
								COUNT(DISTINCT IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0) IN (0,5),H.ID,NULL)) AS MO_CEVAP_BEKLEYEN_DOSYA_ADET, 
								COUNT(DISTINCT IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0) IN (0,5),AD.ID,NULL)) AS MO_CEVAP_BEKLEYEN_PARCA_ADET, 
								IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0) IN (0,5), DATEDIFF(MAX(IFNULL(AD.MODIFIED_AT,NOW())),MIN(AD.CREATED_AT)),NULL ) AS MO_FARK_CEVAP_BEKLEYEN,
								
								/*GONDERILMEYEN DOSYA*/
								COUNT(DISTINCT IF(HD.ISLEM=1 AND IFNULL(AD.ID,0)=0,H.ID,NULL)) AS MO_GONDERILMEYEN_DOSYA_ADET, 
								COUNT(DISTINCT IF(HD.ISLEM=1 AND IFNULL(AD.ID,0)=0,HD.ID,NULL)) AS MO_GONDERILMEYEN_PARCA_ADET, 
								IF(HD.ISLEM=1 AND IFNULL(AD.ID,0)=0,(DATEDIFF(NOW(),MIN(HD.KAYIT_TARIH_SAAT))),DATEDIFF(NOW(),H.KAYIT_TARIH_SAAT)) AS MO_FARK_GONDERILMEYEN,

								/*MODUL_IPTAL DOSYA*/
								COUNT(DISTINCT IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=3,H.ID,NULL)) AS MO_MODUL_IPTAL_DOSYA_ADET, 
								COUNT(DISTINCT IF( IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=3,AD.ID,NULL)) AS MO_MODUL_IPTAL_PARCA_ADET, 
								IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=3, DATEDIFF(MAX(IFNULL(AD.MODIFIED_AT,NOW())),MIN(AD.CREATED_AT)), NULL) AS MO_FARK_MODUL_IPTAL,

								/*ONARILAN DOSYA*/
								COUNT(DISTINCT IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=1,H.ID,NULL)) AS MO_ONARILAN_DOSYA_ADET, 
								COUNT(DISTINCT IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=1,AD.ID,NULL)) AS MO_ONARILAN_PARCA_ADET, 
								IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=1, DATEDIFF(MAX(IFNULL(AD.MODIFIED_AT,NOW())),MIN(AD.CREATED_AT)), NULL) AS MO_FARK_ONARILAN,
								
								/*ONARILAMAYAN DOSYA*/
								COUNT(DISTINCT IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=2,H.ID,NULL)) AS MO_ONARILAMAYAN_DOSYA_ADET, 
								COUNT(DISTINCT IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=2,AD.ID,NULL)) AS MO_ONARILAMAYAN_PARCA_ADET, 
								IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=2, DATEDIFF(MAX(IFNULL(AD.MODIFIED_AT,NOW())),MIN(AD.CREATED_AT)), NULL) AS MO_FARK_ONARILAMAYAN,
								
								/*DEGERLENDIRILMEYEN DOSYA*/
								COUNT(DISTINCT IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=4,H.ID,NULL)) AS MO_DEGERLENDIRILMEYEN_DOSYA_ADET, 
								COUNT(DISTINCT IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=4,AD.ID,NULL)) AS MO_DEGERLENDIRILMEYEN_PARCA_ADET, 
								IF(IFNULL(AD.ID,0)>0 AND IFNULL(AD.STATUS,0)=4, (DATEDIFF(IFNULL(AD.MODIFIED_AT,NOW()),A.CREATED_AT)),NULL) AS MO_FARK_DEGERLENDIRILMEYEN,
								".( ($this->companyId == 19) ? "
										COUNT(DISTINCT IF(IFNULL(MOP.ID,0)>0,MOI.ID,NULL)) AS MO_IHALE_DOSYA_ADET,
										COUNT(DISTINCT IF(IFNULL(MOP.ID,0)>0,MOP.ID,NULL)) AS MO_IHALE_PARCA_ADET,
										IF(IFNULL(MOP.ID,0)>0, (DATEDIFF(IFNULL(MOI.BITIS_TARIHI,(DATE_SUB(MOI.GONDERIM_TARIHI, INTERVAL -2 DAY))),MOI.GONDERIM_TARIHI)),NULL) AS MO_FARK_IHALE_PARCA,
								" : "" )."												
								1 
						FROM $this->hasarTable H 
						LEFT JOIN HASAR_DETAIL HD ON HD.ONAY_NO = H.ONAY_NO 
						LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME 
						LEFT JOIN AUTOKING A ON A.DOSYA_ID = H.ID 
						LEFT JOIN AUTOKING_USERS AU ON AU.ID = A.AUTOKING_USER_ID
						LEFT JOIN AUTOKING_DETAIL AD ON AD.AUTOKING_ID = A.ID 
						LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
						".( ($this->companyId == 19) ? "
								LEFT JOIN MOBIL_ONARIM_IHALE MOI ON MOI.DOSYA_ID = H.ID
								LEFT JOIN MOBIL_ONARIM_IHALE_PARCALAR MOP ON MOP.IHALE_ID = MOI.ID
						" : "" )."
							WHERE 
								H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
								AND H.USER_EKSPER NOT IN ('EKSPER','ANS001') 
								AND H.PERT != 1 
								AND IFNULL(H.DOSYA_STATU,0) = 0 
								AND H.DOSYA_NO NOT LIKE '%TEST%'
								AND (
								HD.PARCA_ID IN (1,2,10,11,15,20,27,28,43,44,47,49,50,51,52,57,60,62,123,132,301,302,320,321,322,327,334,335,342,343,344,345,347,348,351,358,359,360,369,386,391,526,583,584,649,650,651) 
								OR(HD.GRUP_ID = 2 AND HD.ALT_GRUP IN (586,591,592,595,597,598,599,600,606,608,631,640,1112,1635,1778,1779,1800)) 
								OR(HD.GRUP_ID = 4 AND HD.ALT_GRUP IN (646,650,652,653,654)) 
								OR(HD.GRUP_ID = 10 AND HD.ALT_GRUP IN (687,690))
								OR(HD.GRUP_ID = 12 AND HD.ALT_GRUP = 853)
								)
								$kriter
								$this->kullaniciKriter
						GROUP BY
							H.ID, AU.ID
				) T
				";		
				//ECHO $sql;
			if (!($this->cdb->execute_sql($sql,$result,$error_msg))){return false;}
			$row = mysql_fetch_object($result);
			return $row;	
		}
		
		
		function arastirmaciBlok($ay_basi,$ay_sonu,$sorumlu,$brans,$servis_turu){

			if($this->kullaniciKontrol() == '2' || $this->hdsKullaniciKriter) { return false;}					
			
			if(($sorumlu!=NULL && $sorumlu!=-1)){ 
				$kriter .=  " AND DS.ID='$sorumlu'";
				
			}
			
			if($brans!=NULL && $brans!=-1){ 
				$kriter .=  " AND H.SIGORTA_SEKLI='$brans'";
			}
			
			if($servis_turu==1){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1'";}
			if($servis_turu==2){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0'";}
			if($servis_turu==3){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==4){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==5){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==6){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==7){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==8){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='0'";}
		
			$sql = " 
				SELECT
					COUNT(R.ID) AS ARS_VERILMIS_DOSYA_SAYISI,					
					FORMAT( AVG( DATEDIFF( NOW(), R.VERILIS_TARIH ) ),0) AS DOSYA_ORT_GECEN_SURE,										
					COUNT( DISTINCT IF(DATEDIFF(NOW(), R.VERILIS_TARIH)>30, R.ID, NULL)) AS ARS_VERILMIS_30_DOSYA_SAYISI,										
										
					SUM( IF(R.DURUM = 2, 1, 0) ) AS ARASTIRMACIDA_OLAN_DOSYA_SAYISI,					
					FORMAT ( AVG( IF (R.DURUM = 2, DATEDIFF(NOW(), R.VERILIS_TARIH),NULL) ), 0) AS ARS_GECEN_SURE_ORTALAMA,					
					COUNT( DISTINCT IF(R.DURUM = 2 AND DATEDIFF(NOW(), R.VERILIS_TARIH)>30, R.ID, NULL)) AS ARASTIRMACIDA_30_OLAN_DOSYA_SAYISI,
					
					SUM(IF(R.DURUM = 3, 1, 0)) AS DENETCIDE_OLAN_DOSYA_SAYISI,					
					FORMAT( AVG( IF(R.DURUM = 3, DATEDIFF(NOW(), R.CLOSER_DATE),NULL) ), 0) AS DEN_GECEN_SURE_ORTALAMA,
					COUNT( DISTINCT IF(R.DURUM = 3 AND DATEDIFF(NOW(), R.CLOSER_DATE)>30, R.ID, NULL)) AS DENETCIDE_30_OLAN_DOSYA_SAYISI,
					
					SUM(IF(R.DURUM = 5, 1, 0)) AS IPTAL_DOSYA_SAYISI,				
					FORMAT( AVG( IF(R.DURUM = 5, DATEDIFF(NOW(), R.CLOSER_DATE),NULL) ), 0) AS IPTAL_SURE_ORTALAMA,
					COUNT( DISTINCT IF(R.DURUM = 3 AND DATEDIFF(NOW(), R.CLOSER_DATE)>30, R.ID, NULL)) AS IPTAL_30_OLAN_DOSYA_SAYISI,
					
					SUM(IF(R.DURUM = 4, 1, 0)) AS TAMAMLANMIS_DOSYA_SAYISI,			 
					FORMAT (AVG(IF(R.DURUM = 4, DATEDIFF(R.DENETCI_CLOSER_DATE, R.VERILIS_TARIH),NULL)),0) AS TAMAMLANMIS_DOSYA_SAYISI_30ORTALAMA,
					COUNT( DISTINCT IF(R.DURUM = 3 AND DATEDIFF(R.DENETCI_CLOSER_DATE, R.VERILIS_TARIH)>30, R.ID, NULL)) AS TAMAMLANMIS_30_OLAN_DOSYA_SAYISI
					
				FROM HASAR_ARASTIRMA_RAPOR AS R
				INNER JOIN $this->hasarTable AS H ON H.ID = R.DOSYA_ID
				LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME
				LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU 
				WHERE		
						R.VERILIS_TARIH  BETWEEN '".$ay_basi."' AND '".$ay_sonu."'							
						AND H.DOSYA_NO NOT LIKE '%TEST%'
						$kriter
						$this->kullaniciKriter
				";	
				//ECHO $sql;  Die;
			if (!($this->cdb->execute_sql($sql,$result,$error_msg))){return false;}
			$row = mysql_fetch_object($result);
			return $row;	
		}
		
		function uzmanBlok($ay_basi,$ay_sonu,$sorumlu,$brans,$servis_turu){
		
			if( ($this->kullaniciKontrol() == '2' || $this->hdsKullaniciKriter) ) { return false;}		
		
			if(($sorumlu!=NULL && $sorumlu!=-1)){ 
				$kriter .=  " AND DS.ID='$sorumlu'";
				
			}
			
			if($brans!=NULL && $brans!=-1){ 
				$kriter .=  " AND H.SIGORTA_SEKLI='$brans'";
			}
			
			if($servis_turu==1){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1'";}
			if($servis_turu==2){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0'";}
			if($servis_turu==3){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==4){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==5){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==6){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==7){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==8){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='0'";}
		
			$sql = " 
				SELECT * FROM 
				(
					SELECT 
						COUNT( H.ID ) AS TOPLAM_DOSYA_ADET,
						COUNT( DISTINCT IF ( IFNULL( H.USER_UZMAN, '' ) != '', H.ID, NULL ) ) AS UZMAN_ATANAN_ADET,
						FORMAT( AVG( IF ( IFNULL( H.USER_UZMAN, '' ) != '', DATEDIFF( NOW(), H.EKSPER_UZMAN_TARIH )  ,NULL)), 0 ) AS UZMAN_ATANAN_ORT_SURE,						
						COUNT( IF ( IFNULL( H.USER_UZMAN, '' ) != '' AND DATEDIFF( NOW(), H.EKSPER_UZMAN_TARIH )>30, H.ID, NULL ) ) AS UZMAN_ATANAN_30_ADET,		

						COUNT( DISTINCT HUK.ID ) AS ARAC_SERVISTE_GORULMEYENLER,
						FORMAT( AVG( IF (  HUK.ID , DATEDIFF( NOW(), HUK.TARIH)  ,NULL)),0) AS ARAC_SERVISTE_GORULMEYENLER_ORT_SURE,
						COUNT( DISTINCT IF ( HUK.ID AND DATEDIFF( NOW(), HUK.TARIH)>30, HUK.ID, NULL ) ) AS ARAC_SERVISTE_GORULMEYENLER_30_ADET,					
						
						COUNT( DISTINCT IF ( IFNULL(K1.ID,0) > 0 AND K1.KONTROL=1, H.ID, NULL ) ) AS BIRINCI_KONTROL_ADET,
						FORMAT( AVG( IF ( K1.KONTROL=1, DATEDIFF( NOW(), H.EKSPER_UZMAN_TARIH ) ,NULL)),0) AS BIRINCI_KONTROL_ORT_SURE,
						COUNT(  IF ( IFNULL(K1.ID,0) > 0 AND K1.KONTROL=1 AND DATEDIFF( NOW(), H.EKSPER_UZMAN_TARIH )>30, H.ID, NULL ) ) AS BIRINCI_KONTROL_30_ADET,					
						
						COUNT( DISTINCT  IF ( IFNULL(K1.ID,0) > 0  AND K1.KONTROL=2, H.ID, NULL ) ) AS IKINCI_KONTROL_ADET,
						FORMAT( AVG( IF ( IFNULL(K1.ID,0) > 0  AND K1.KONTROL=2, DATEDIFF( NOW(), H.EKSPER_UZMAN_TARIH ) ,NULL)),0) AS IKINCI_KONTROL_ORT_SURE,
						COUNT(  IF ( IFNULL(K1.ID,0) > 0  AND K1.KONTROL=2 AND DATEDIFF( NOW(), H.EKSPER_UZMAN_TARIH )>30, H.ID, NULL ) ) AS IKINCI_KONTROL_30_ADET,
						
						COUNT( DISTINCT  IF( H.DOSYA_STATU = 1  AND H.USER_UZMAN IS NOT NULL  AND IFNULL( H.UZMAN_ONAY, 0 ) <> 1, H.ID,NULL ) ) AS EKSPER_KAPALI_UZMAN_ONAY_BEKLEYEN_ADET,
						FORMAT( AVG( IF ( H.DOSYA_STATU = 1  AND H.USER_UZMAN IS NOT NULL  AND IFNULL( H.UZMAN_ONAY, 0 ) <> 1, DATEDIFF( NOW(), H.EKSPER_UZMAN_TARIH ) ,NULL)),0) AS EKSPER_KAPALI_UZMAN_ONAY_BEKLEYEN_ORT_SURE,
						COUNT(  IF( H.DOSYA_STATU = 1  AND H.USER_UZMAN IS NOT NULL  AND IFNULL( H.UZMAN_ONAY, 0 ) <> 1 AND DATEDIFF( NOW(), H.EKSPER_UZMAN_TARIH )>30, H.ID,NULL ) ) AS EKSPER_KAPALI_UZMAN_ONAY_BEKLEYEN_30_ADET,
						1		
					FROM
						$this->hasarTable H						
						LEFT JOIN UZMAN_KONTROL AS K1 ON K1.ONAY_NO = H.ONAY_NO	
						LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME
						LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU 
						LEFT JOIN HASAR_UZMAN_KONTROL HUK ON HUK.ONAY_NO=H.ONAY_NO AND ACIK_NOTU='Araç Serviste Bulunamadý'
					WHERE		
							H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
							AND H.DOSYA_NO NOT LIKE '%TEST%'
							AND IFNULL(H.UZMAN_ONAY ,0) != 1
							$kriter
							$this->kullaniciKriter
				) AS T1
				CROSS JOIN
				(
					SELECT						
						COUNT( DISTINCT IF (IFNULL(PH.ID,0) > 0, H.ID, NULL ) ) AS EVRAK_YUKLENEN_ADET,
						FORMAT( AVG( IF (  IFNULL(PH.ID,0) > 0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )  ,NULL)),0) AS EVRAK_YUKLENEN_ORT_SURE,
						COUNT( DISTINCT IF ( IFNULL(PH.ID,0) > 0 AND DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )>30, H.ID, NULL ) ) AS EVRAK_YUKLENEN_30_ADET
					FROM
						PHOTO_ARCHIVE PH
						INNER JOIN $this->hasarTable H ON H.ONAY_NO = PH.ONAY_NO
						LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME
						LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU 
					WHERE
						H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
						AND H.DOSYA_NO NOT LIKE '%TEST%'
						AND IFNULL(H.UZMAN_ONAY,0) != 1
						AND H.USER_UZMAN IS NOT NULL
						AND PH.USERNAME = H.USER_UZMAN
						$kriter
						$this->kullaniciKriter
				) AS T2
				CROSS JOIN
				(
					SELECT
						COUNT( DISTINCT IF (IFNULL(PH.ID,0) =0, H.ID, NULL ) ) AS EVRAK_YUKLENMEYEN_ADET,
						FORMAT( AVG( IF (  IFNULL(PH.ID,0) =0, DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )  ,NULL)),0) AS EVRAK_YUKLENMEYEN_ORT_SURE,
						COUNT( DISTINCT IF ( IFNULL(PH.ID,0) =0 AND DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )>30, H.ID, NULL ) ) AS EVRAK_YUKLENMEYEN_30_ADET										
					FROM						
						$this->hasarTable H 
						LEFT JOIN PHOTO_ARCHIVE PH ON H.ONAY_NO = PH.ONAY_NO
						LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME
						LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU 
					WHERE
						H.KAYIT_TARIH_SAAT BETWEEN '".$ay_basi." 00:00:00' AND '".$ay_sonu." 23:59:59'
						AND H.DOSYA_NO NOT LIKE '%TEST%'
						AND IFNULL(H.UZMAN_ONAY,0) != 1
						AND H.USER_UZMAN IS NOT NULL						
						$kriter
						$this->kullaniciKriter
				) AS T3				
				";	
				//if(dbg()) { echo $sql; die;} 
			if (!($this->cdb->execute_sql($sql,$result,$error_msg))){return false;}
			$row = mysql_fetch_object($result);
			return $row;	
		}
		
		function alternatifTamirBlok($ay_basi,$ay_sonu,$sorumlu,$brans,$servis_turu){
		
			if($this->kullaniciKontrol() == '2' || $this->hdsKullaniciKriter) { return false;}		
		
			if(($sorumlu!=NULL && $sorumlu!=-1)){ 
				$kriter .=  " AND DS.ID='$sorumlu'";
				
			}
			
			if($brans!=NULL && $brans!=-1){ 
				$kriter .=  " AND H.SIGORTA_SEKLI='$brans'";
			}
			
			if($servis_turu==1){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1'";}
			if($servis_turu==2){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0'";}
			if($servis_turu==3){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==4){ $kriter .=  " AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==5){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==6){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='1'";}
			if($servis_turu==7){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='1' AND IFNULL(H.ANLASMALI, 0)='0'";}
			if($servis_turu==8){ $kriter .=  " AND IFNULL(H.SERVIS_TUR_ID, 0)='0' AND IFNULL(H.ANLASMALI, 0)='0'";}
			
			
			$sql = " 
					SELECT
						COUNT(TA.ID) AS TOPLAM_DOSYA_ADET,
						FORMAT( AVG( IF ( TA.ID , DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )  ,NULL)),0) AS DOSYA_ORT_GECEN_SURE,						
						COUNT(DISTINCT IF ( TA.ID AND DATEDIFF(NOW(), H.KAYIT_TARIH_SAAT)> 30, H.ID,NULL)) DOSYA_30_GECEN_SURE,
						
						COUNT(CASE WHEN TA.DURUM_ID= '1' THEN 1 END) AS TEKLIFE_CIKACAKLAR,
						FORMAT( AVG( IF ( TA.DURUM_ID= '1', DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )  ,NULL)),0) AS TEKLIFE_CIKACAKLAR_ORT_GECEN_SURE,						
						COUNT(DISTINCT IF (TA.DURUM_ID= '1' AND DATEDIFF(NOW(), H.KAYIT_TARIH_SAAT)> 30, H.ID,NULL)) TEKLIFE_CIKACAKLAR_30_GECEN_SURE,

						COUNT(CASE WHEN TA.DURUM_ID= '2' THEN 1 END) AS TEKLIF_TOPLAMADA_OLANLAR,
						FORMAT( AVG( IF ( TA.DURUM_ID= '2', DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )  ,NULL)),0) AS TEKLIFE_CIKACAKLAR_ORT_GECEN_SURE,						
						COUNT(DISTINCT IF (TA.DURUM_ID= '2' AND DATEDIFF(NOW(), H.KAYIT_TARIH_SAAT)> 30, H.ID,NULL)) TEKLIFE_CIKACAKLAR_30_GECEN_SURE,

						COUNT(CASE WHEN TA.DURUM_ID= '6' THEN 1 END) AS TEKLIF_VEREN_ANLASMALI_SERVISTE_TAMIR_OLANLAR,
						FORMAT( AVG( IF ( TA.DURUM_ID= '6', DATEDIFF( NOW(), H.KAYIT_TARIH_SAAT )  ,NULL)),0) AS TEKLIFE_CIKACAKLAR_ORT_GECEN_SURE,						
						COUNT(DISTINCT IF (TA.DURUM_ID= '6' AND DATEDIFF(NOW(), H.KAYIT_TARIH_SAAT)> 30, H.ID,NULL)) TEKLIFE_CIKACAKLAR_30_GECEN_SURE
					FROM
						$this->hasarTable H
						LEFT JOIN USERS U ON H.USER_EKSPER = U.U_NAME
						INNER JOIN TAMIRHANE_ARACLAR TA ON H.ONAY_NO = TA.ONAY_NO
						INNER JOIN TAMIRHANE_DOSYA_DURUM TDD ON TDD.ID = TA.DURUM_ID
						LEFT JOIN DOSYA_SORUMLULARI DS ON DS.ID = H.DOSYA_SORUMLUSU
					WHERE					
						TA.TARIH BETWEEN '".$ay_basi."' AND '".$ay_sonu."'
						AND IFNULL(H.DOSYA_STATU,0) = 0		
						AND H.DOSYA_NO NOT LIKE '%TEST%'					
						$kriter
						$this->kullaniciKriter
				";	
				//echo($sql);
			if (!($this->cdb->execute_sql($sql,$result,$error_msg))){return false;}
			$row = mysql_fetch_object($result);
			return $row;	
		}
		
		function modul_aktif_kontrol(){
			
			$modul_eksper				= false;
			$modul_servis				= false;
			$modul_faturali 			= false; 
			$modul_cam 					= false; 
			$modul_tedarik				= false; 
			$modul_mobil				= false; 			
			$modul_otodisi 				= false;
			$modul_arastirmaci 			= false;
			$modul_uzman 				= false;
			$modul_alternatif_tamir 	= false;
			
			//firma id lere göre aktif mi kontrol ediliyor.
			$eksper_aktif_modul_kontrol				= array(18,19,20,23,24,27,28,30,32,37,42,44,47,48,49,50,51,55,56,58,60,64,70,75,80,143,144,145,156);
			$servis_aktif_modul_kontrol				= array(18,19,20,27,28,30,37,42,44,47,50,55,56,64,75,143,144,145,156);
			$faturali_aktif_modul_kontrol			= array(18,19,20,24,28,30,42,44,47,48,49,50,55,56,60,64,70,75,80,143,144,145,156);
			$cam_aktif_modul_kontrol				= array(19,24,27,28,30,32,37,42,44,47,48,50,55,56,58,64,75,80,143,144,145,156);
			$tedarik_aktif_modul_kontrol			= array(18,19,20,23,24,27,28,30,32,37,42,44,47,48,49,50,51,55,56,58,60,64,70,75,80,143,144,145,156);
			$mobil_aktif_modul_kontrol				= array(18,19,20,23,24,27,28,30,32,37,42,44,47,48,49,50,51,55,56,58,60,64,70,75,80,143,144,145,156);
			$otodisi_aktif_modul_kontrol 			= array(27,18,30,28,24,51,56,19,23,20,37,32,70,143,55,47,75,58,64);			
			$arastirmaci_aktif_modul_kontrol 		= array(19,20,23,24,28,32,42,44,47,48,51,55,56,58,60,64,80);
			$uzman_aktif_modul_kontrol 				= array(27,49,24,19,23,20,50,37,70,55,47,75);
			$alternatif_tamir_aktif_modul_kontrol	= array(20,30,44);
			$teknik_incelemeci_aktif_modul_kontrol	= array(19);
			
			
			if(in_array($this->companyId,$eksper_aktif_modul_kontrol)) 			{ $modul_eksper = true; }
			if(in_array($this->companyId,$servis_aktif_modul_kontrol)) 			{ $modul_servis = true; }
			if(in_array($this->companyId,$faturali_aktif_modul_kontrol)) 		{ $modul_faturali = true; }			
			if(in_array($this->companyId,$cam_aktif_modul_kontrol)) 			{ $modul_cam = true; }			
			if(in_array($this->companyId,$tedarik_aktif_modul_kontrol)) 		{ $modul_tedarik = true; }			
			if(in_array($this->companyId,$mobil_aktif_modul_kontrol)) 			{ $modul_mobil = true; }			
			if(in_array($this->companyId,$otodisi_aktif_modul_kontrol)) 		{ $modul_otodisi = true; }
			if(in_array($this->companyId,$arastirmaci_aktif_modul_kontrol)) 	{ $modul_arastirmaci = true; }
			if(in_array($this->companyId,$uzman_aktif_modul_kontrol))			{ $modul_uzman = true; }			
			if(in_array($this->companyId,$alternatif_tamir_aktif_modul_kontrol)){ $modul_alternatif_tamir = true; }
			if(in_array($this->companyId,$teknik_incelemeci_aktif_modul_kontrol)){ $modul_teknik_incelemeci = true; }			
			
			$return_modul = array(
			'modul_eksper'=>$modul_eksper,
			'modul_servis'=>$modul_servis,			
			'modul_faturali'=>$modul_faturali,
			'modul_cam'=>$modul_cam,
			'modul_tedarik'=>$modul_tedarik,
			'modul_mobil'=>$modul_mobil,
			'modul_otodisi'=>$modul_otodisi,
			'modul_arastirmaci'=>$modul_arastirmaci,
			'modul_uzman'=>$modul_uzman,
			'modul_alternatif_tamir'=>$modul_alternatif_tamir,
			'modul_teknik_incelemeci' => $modul_teknik_incelemeci,				
			);
			return $return_modul;
			
		}

	}
	
?>